### ISSUE TITLE
Broaden bulkAddEdges to accept Iterable<Pair<L, R>>

### ISSUE THREAD

**Issue by jgustie** [pietermartin/sqlg#102]
The existing implementation of `bulkAddEdges` requires a `List`; from what I can see the list is used in a for-each loop and there is an empty test on it. It would be useful to pass in an arbitrary iterable to this method. Even a `Collection` would be ok (which keeps `size()` and `isEmpty()` available).

**Comment by pietermartin** [comment]
So `Collection` will do?

**Comment by jgustie** [comment]
Yeah, `Collection` works and is way easier to implement.
