### ISSUE TITLE
Batch mode fails creating "empty" item

### ISSUE THREAD

**Issue by JPMoresmau** [pietermartin/sqlg#103]
This code:

```
Vertex person1 = this.sqlgGraph.addVertex(T.label, "Empty","empty","");
this.sqlgGraph.tx().commit();
```

Works fine in normal mode but not in batch mode, because we end up with an empty CSV. So no row is created, causing a `java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: currval of sequence "V_Empty_ID_seq" is not yet defined in this session` error. Unlikely scenario I know but for some reason we stumbled on it.

**Comment by pietermartin** [comment]
I'd have to look but somewhere there is code that created a dummy key for a similar scenario.

**Comment by pietermartin** [comment]
Looked at your PR, the dummy I referred to is think was for when there are no properties.
