### ISSUE TITLE
Path without start vertex

### ISSUE THREAD

**Issue by imhy** [pietermartin/sqlg#121]
Hi, Pieter!

I try to run this query to find all paths, But I get some paths without start vertex
 [e[public.tsw:::1][public.vertex:::1-tsw->public.vertex:::2], v[public.vertex:::2]]

Query:

Function timeAtWarehouse = new Function() {
	@Override
	public Long apply(Object o) {
		Map m = (Map) o;
		Integer dow = ((Edge) (m.get("prev"))).value("dow");
		Long readyTime = ((Edge) (m.get("prev"))).value("readyTime");
		Integer depDow = ((Edge) (m.get("curr"))).value("dow");
		Long depTime = ((Edge) (m.get("curr"))).value("depTime");
		return weekHlp.timeAtWarehouse(dow, readyTime, depDow, depTime); // always   > 0
	}
};

 g.V().outE("tsw").as("e").inV().emit().repeat(
		__.flatMap(
				__.outE("tsw").filter(__.as("edge").select(last, "e").where(P.eq("edge")).by("speed")).
						group().by(__.inV()).by(__.project("curr", "prev").by().by(__.select(last, "e")).fold()).
						select(Column.values).unfold().order(local).by(timeAtWarehouse).limit(local, 1).select("curr")
		).as("e").inV().simplePath()
).times(maxPathLength + 1).map(__.union((Traversal) __.select(last, "e").by("speed"), (Traversal) __.path()).fold());

Database attached:
[sqlg_test.backup.zip](https://github.com/pietermartin/sqlg/files/639388/sqlg_test.backup.zip)

Regards, Sergei.

**Comment by pietermartin** [comment]
The .zip file seems corrupted as I can not extract it. Can you retry, thanks.

**Comment by imhy** [comment]
I put it to google.drive, please try.
https://drive.google.com/open?id=0B2j8ixtPgxmqOGtjRGE5eWpwbHc

**Comment by pietermartin** [comment]
Ok I see its a postgresql dump file.
It be way easier for me if you can write a failing test however.
That way I can compare it to TinkerGraph and in general its easier.

I imported the dump but the code you give does not compile. `weekHlp` and `maxPathLength` are not defined.

**Comment by imhy** [comment]
weekHlp  - can be replaced to any non negative value for example 10000L
maxPathLength  in my case = 20.

Ok, I will try to create test with TinkerGraph.
—

**Comment by pietermartin** [comment]
Say @imhy , did you get any further with this?

**Comment by imhy** [comment]
Say @pietermartin , sorry at this moment no. I will try to do test with TinkerGraph at this week.

**Comment by imhy** [comment]
Hi!
Please, can You try this test:
https://gist.github.com/imhy/fcc6ef160facd6321aff06f6473b3a0b

All paths that I get using sqlg query has missing start vertex. (path start from edge element).
For example output 
first result on sqlg:
[e[public.tsw:::1][public.vertex:::1-tsw->public.vertex:::2], v[public.vertex:::2]]
first result on tinkergraph
[v[0], e[8][0-tsw->2], v[2]]

I`m using Sqlg 1.3.3-SNAPSHOT.

Regards, Sergei.

**Comment by pietermartin** [comment]
ok great tx

**Comment by pietermartin** [comment]
Same issue as #116, reopening that one.
