### ISSUE TITLE
Indices issues: non public schemas, not reread on startup

### ISSUE THREAD

**Issue by JPMoresmau** [pietermartin/sqlg#129]
sqlgGraph.createVertexLabeledIndex does not handle labels prefixed by the schema. That's easy to fix. Another issue is that even though createVertexLabelIndex works fine if invoked several times in a row, as TestIndex.testIndexExist() shows, indices are not persisted in the topology over restarts, so closing the graph, reopening it and recreating the index fails (I've modified the test to show that).
I think the index definitions are captured in the topology (TopologyManager.addIndex) so what's missing is for this information to be read back when we do a cacheTopology, right?

**Comment by pietermartin** [comment]
Yes, the bug, or missing code would be in `SqlgStartupManager.loadSchema`.
It is responsible to load the schema at startup.

If `sqlg_schema` does not exist then from `information_schema` else from the `sqlg_schema`
