### ISSUE TITLE
ZonedDateTime property issues in SqlgElement

### ISSUE THREAD

**Issue by jgustie** [pietermartin/sqlg#134]
I have a simple test where I set a property to a `ZonedDateTime` instance and it fails with an NPE when using 1.3.2:

````
sqlgGraph.addVertex("Test").property("ts", ZonedDateTime.now());
sqlgGraph.tx().commit();
sqlgGraph.traversal().V().has("ts").next();
````

The NPE comes from `SqlgElement.loadProperty` because the `zoneId` string from the database comes back as `null` and is then passed into `ZoneId.of(String)` (this turns out to be more of a symptom then an actual problem though).

The reason that the zone ID column is `null` is because `SqlgElement.updateRow` only generates a SQL query to UPDATE the "ts" column (`UPDATE "public"."V_Test" SET "ts" = ? WHERE "ID" = ?;`). It looks like the `setKeyValuesAsParameter` is actually doing the right thing and tries to include the zone, but in this case the zone gets overridden by the record ID in `updateRow`.

Capturing the return value of `setKeyValuesAsParameter` and using that to set the record ID parameter number would fix the problem with overwriting the zone ID value, but the generated query would still need to include the extra column update for the time zone.

**Comment by pietermartin** [comment]
That has been fixed on the master branch already. Part of #56 

As a work around you can, 

1. Add the vertex with the property. i.e. 
```
    @Test
    public void test2() {
        ZonedDateTime zdt = ZonedDateTime.now();
        sqlgGraph.addVertex(T.label, "Test", "ts", zdt);
        sqlgGraph.tx().commit();
        ZonedDateTime ts = sqlgGraph.traversal().V().has("ts").next().value("ts");
        assertEquals(zdt, ts);
    }

```
2. Update the property in batch mode.
```
    @Test
    public void test1() {
        ZonedDateTime zdt = ZonedDateTime.now();
        this.sqlgGraph.tx().normalBatchModeOn();
        sqlgGraph.addVertex("Test").property("ts", zdt);
        sqlgGraph.tx().commit();
        ZonedDateTime ts = sqlgGraph.traversal().V().has("ts").next().value("ts");
        assertEquals(zdt, ts);
    }

```

**Comment by jgustie** [comment]
Awesome, thanks!
