### ISSUE TITLE
Support topology rename and delete

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#137]
The current topology only supports adding.
Renaming and deleting elements should be supported.
Doing this via sql makes the topology cache go out of sync with the db and requires a restart to sync again.

**Comment by JPMoresmau** [comment]
https://github.com/JPMoresmau/sqlg/tree/feature/137_topology_update

**Comment by pietermartin** [comment]
This has been implemented.
https://github.com/pietermartin/sqlg/commit/7b31bf431adab63e553ba443775b2b2484a806a0
