### ISSUE TITLE
TopologyListener limitations

### ISSUE THREAD

**Issue by JPMoresmau** [pietermartin/sqlg#152]
I think there are some limitations on TopologyListener
- getSchema on AbstractLabel is not public, while a listener probably needs to know in which schema a new label has been created
- in the same way, Index should probably expose its AbstractLabel
- it seems that even though the topology changes are broadcast when in distributed mode, we do not fire listeners when we apply the changes via the JSON. So a topology listener only hears of the changes made in its own JVM.

**Comment by pietermartin** [comment]
Yeah I agree.
It was a rather quick initial implementation to get past the `PreparedStatement` issues with the new jdbc driver.

**Comment by pietermartin** [comment]
Something to be aware of when firing the listener in the other JVM is that the transaction is already committed.
In the original JVM the listener fires before the transaction commits.
