### ISSUE TITLE
install org.umlg sqlg-postgres exception

### ISSUE THREAD

**Issue by gflp123** [pietermartin/sqlg#168]
install org.umlg sqlg-postgres exception

E:\Graph\apache-tinkerpop-gremlin-console-3.2.3\bin>gremlin.bat

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> :install org.umlg sqlg-postgres 1.3.3-SNAPSHOT
log4j:WARN No appenders could be found for logger (org.apache.tinkerpop.gremlin.
groovy.util.DependencyGrabber).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more in
fo.
==>Conflicting module versions. Module [groovy-xml is loaded in version 2.4.7 an
d you are trying to load version 2.4.8
gremlin>

**Comment by pietermartin** [comment]
Sqlg 1.3.3-SNAPSHOT is running on TinkerPop 3.2.4
Looks like you are trying 3.2.3 gremlin console.

**Comment by pietermartin** [comment]
@gflp123 did you come right?
