### ISSUE TITLE
Graph databases or sqlg

### ISSUE THREAD

**Issue by gflp123** [pietermartin/sqlg#171]
Deal with Master Data Manager,Using Graph Database(neo4j、orientdb、titian) or sqlg(postgresql).

How to choice.Thanks

**Comment by pietermartin** [comment]
You'll have to give me more information. Not sure what you mean with 'Master Data Manager'?

In general I would suggest Sqlg if your company already has a investment in a RDBMs  technology and if the kind of data structures you have is not highly hierarchical. I.e. if you are doing social media friend of friend type of data then I would not advice using Sqlg.

Titan is dead, go for Janus graph rather if you do not need transactions and need a distributed architecture.
Neo4j is very good but not for free and to be honest if I were to use Neo4j then I'd go with their query language being Cypher.

I have no experience with OrientDB.

As per normal I'd run some tests, especially testing the kind of queries you would like to run.
Sqlg on Posgres is very good at loading data, but not all gremlin's can be optimized.
