### ISSUE TITLE
SqlgStartupManager.extractIndices is slow

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#184]
I ran the latest master branch with the `SqlgStartupManager.extractIndices` code on at the day job's system. It is a large system with 25 000 tables or so.
The startup time for loading `sqlg_schema` from the `information_schema` has drastically slowed. From 8 minutes to 3 hours or so.

Need to look at speeding it up, perhaps by loading all the index information upfront as opposed to per table.

**Comment by JPMoresmau** [comment]
getIndexInfo does not support a null table name, you HAVE to provide a table name. I've done a test with 1000 tables, without indices it loads in 7 seconds, with indices in 48 seconds, so yes it's really slow. The postgresql implementation seems to be quite complex and hence slow... No idea really what could be done at the moment...

**Comment by JPMoresmau** [comment]
Of course we could reuse the postgresql code as is and just see if we can remove the table filter. I'll see if it's faster.

**Comment by JPMoresmau** [comment]
Have a look at https://github.com/JPMoresmau/sqlg/tree/perf/indices_load. The test still passes, and it loads indices 4 times faster when there are 1000 tables. Ca you maybe test in your big environment?

**Comment by pietermartin** [comment]
Great tx. I am on holiday, so will only get a chance by the weekend to have a look.

**Comment by pietermartin** [comment]
I am testing this now but `TestTopologyUpgrade.testUpgrade` is failing.
I am having a look at it.

**Comment by pietermartin** [comment]
Looks like an accidental `TopologyManager.addVertexLabel` sliped in the loading of edge properties.

**Comment by JPMoresmau** [comment]
Damn sorry. I saw the failure and then forgot about it

**Comment by pietermartin** [comment]
I am just running the test, will push the fix soon

**Comment by pietermartin** [comment]
Ok, our system now starts up in 12 minutes which is fine.
Quite the query you had to hack for this.
There was a bug in `TopologyManager.addIndex` where it loads duplicate edges.
I have fixed it by adding in a `dedup()` and added a test case.
