### ISSUE TITLE
please use Apache 2.0 instead of MIT

### ISSUE THREAD

**Issue by fommil** [pietermartin/sqlg#188]
Could you please consider using Apache 2.0 instead of MIT. Yes, MIT is shorter, but those extra clauses are there to give a lot of protection to end users, e.g. see my short talk on this http://fommil.com/scalasphere16/

TL;DR Apache 2.0 gives users the patent rights (if anybody were to add any) whereas MIT does not.

**Comment by pietermartin** [comment]
Ok, as you say I kinda went for the shortest one.

**Comment by fommil** [comment]
Thanks!

**Comment by pietermartin** [comment]
Out of curiosity, are you using Sqlg?

**Comment by fommil** [comment]
Considering using it in ensime, but I think we might stick with orientdb for now. The problem with h2 is row deletion performance.

**Comment by pietermartin** [comment]
Ok thanks
