### ISSUE TITLE
sqlg vs titan?

### ISSUE THREAD

**Issue by danyaljj** [pietermartin/sqlg#19]
I am trying to save a big DAG on disk and query it. 
Any advice on whether it is better to use Titan (https://github.com/thinkaurelius/titan/) or sqlg (or when to use either)?

**Comment by pietermartin** [comment]
Sqlg and Titan have very very different backends.
Sqlg, in theory, can run on any rdbms, in practise only Postgresql and HSQLDB are supported. 
Titan runs on top of Cassandra.

Cassandra is massively horizontally scalable, Postgresql is not.
Cassandra does not support transactions, Postgresql does.
I'd suggest investigating both as they are so different.

Sql as a language is far more well known than gremlin. This means that the database is accessible to all sorts of clients without them needing to learn gremlin. 

Titan/Neo4j/OrientDb are more mature with active communities. 
If you like/want sql and would like to use Postgresql/HSQLDB then Sqlg is the only option I know of.
