### ISSUE TITLE
HSQLDB tests are failing

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#197]
Hsqldb tests are failing with the schema creation command.
`SqlDialect.createSchemaStatement` is now `CREATE SCHEMA IF NOT EXISTS ` while it used to be `CREATE SCHEMA ` only.
The `PostgresDialect` has the ` IF NOT EXISTS`
Hsqldb does not support the `IF NOT EXISTS`

**Comment by JPMoresmau** [comment]
Oops sorry, I only test with Postgres, and I thought the IF NOT EXISTS was supported everywhere
