### ISSUE TITLE
Re-use Features

### ISSUE THREAD

**Issue by spmallette** [pietermartin/sqlg#20]
A minor suggestion, but I happened to notice that sqlg creates new `Feature` instances whenever they are used...for example:

https://github.com/pietermartin/sqlg/blob/master/sqlg-core/src/main/java/org/umlg/sqlg/structure/SqlgGraph.java#L395

That will create a lot of throwaway objects as there are many internal methods that make numerous calls for feature checking.  Better to create one instance and re-use it if possible.

**Comment by pietermartin** [comment]
Done, tx.
