### ISSUE TITLE
Upgrade documentation

### ISSUE THREAD

**Issue by s-nel** [pietermartin/sqlg#207]
The docs at http://umlg.org/sqlg.html are quite out of date.

**Comment by pietermartin** [comment]
www.sqlg.org has the latest, it too needs updating of some new features but is a lot newer

**Comment by pietermartin** [comment]
www.sqlg.org has the latest, it too needs updating of some new features but is a lot newer

**Comment by s-nel** [comment]
Oh my mistake. Thanks
