### ISSUE TITLE
prefixedTable must be for an edge

### ISSUE THREAD

**Issue by s-nel** [pietermartin/sqlg#210]
In 1.3.3 with H2 url the `loadSqlgSchemaFromInformationSchema` method has an issue where it mistakenly identifies tables that begin with the letter e as an edge table.

E.g. I have a table "event" in my database, and I get an error:

```
[info]   Cause: java.lang.IllegalArgumentException: prefixedTable must be for an edge. prefixedTable = EVENT
[info]   at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[info]   at org.umlg.sqlg.structure.TopologyManager.addEdgeColumn(TopologyManager.java:611)
[info]   at org.umlg.sqlg.structure.TopologyManager.addEdgeColumn(TopologyManager.java:604)
[info]   at org.umlg.sqlg.structure.SqlgStartupManager.loadSqlgSchemaFromInformationSchema(SqlgStartupManager.java:317)
[info]   at org.umlg.sqlg.structure.SqlgStartupManager.loadSchema(SqlgStartupManager.java:70)
[info]   at org.umlg.sqlg.structure.SqlgGraph.open(SqlgGraph.java:228)
[info]   at org.umlg.sqlg.structure.SqlgGraph.open(SqlgGraph.java:217)
[info]   at spring.marketintel.graphdb.SqlgGraphFactory.createGraph(GraphFactory.scala:31)
[info]   at spring.marketintel.db.migrations.db.migration.V2__data_import_v1.$anonfun$migrate$2(V2__data_import_v1.scala:24)
[info]   at fs2.Task$.$anonfun$delay$1(Task.scala:191)
```

From inspection I can see the reason is because the table prefix matching in `loadSqlgSchemaFromInformationSchema` uses `"E_%"` and `"V_%"`. When part of a `LIKE` clause, the underscore character matches any single character, so that pattern will match any tables beginning with the letter 'e' and the letter 'v', respectively. I can think of a couple solutions. Either try to escape the underscore and test that it works in all the supported dbms (probably not dbms agnostic), or add a redundant filter in `loadSqlgSchemaFromInformationSchema` that verifies each table matches the prefix.

**Comment by pietermartin** [comment]
fixed by https://github.com/pietermartin/sqlg/issues/210
