### ISSUE TITLE
ensureSchemaExist does not properly escape the schema name

### ISSUE THREAD

**Issue by Easy65** [pietermartin/sqlg#216]
Hello,

I discovered a security issue in class Topology, method ensureSchemaExist. It finally creates the schema in class Schema, method createSchemaOnDb. This calls the following method to write the escaped schema name to the SQL string:

sql.append(this.sqlgGraph.getSqlDialect().maybeWrapInQoutes(this.name));

This uses the following code in class SqlDialect to escape the schema name:

default String maybeWrapInQoutes(String field) {
        return getColumnEscapeKey() + field + getColumnEscapeKey();
}

So the original parameter to ensureSchemaExist must not be escaped.

If I use the following schema name:

TestDeleteDataSchema";commit;drop database "TestSQLInjection

the call will drop the database TestSQLInjection.

Of cource the  caller can (and maybe should) check input from unknown sources, but I think it should also do proper escaping here, because it results (in addition to the SQL injection problem) in inconsistent data: 

I see in the V_schema table the value

TestDeleteDataSchema";commit;drop database "TestSQLInjection

in the text column, but it creates the schema TestDeleteDataSchema.

**Comment by pietermartin** [comment]
ha, never in considered sql injection.
thanks

**Comment by pietermartin** [comment]
This has been fixed.
I escape the embedded quote. Added a test to `TestSchema`
If you know of another way to inject sql please let me know.
Thanks

**Comment by Easy65** [comment]
Thanks.
