### ISSUE TITLE
ID restriction and hasLabel() conditions does not work together

### ISSUE THREAD

**Issue by LotharGrabowsky** [pietermartin/sqlg#219]
Assume a vertex a with label A and a vertex b with label B. Now we drive a query with an ID restriction and a label condition, e.g. `sglgGraph.traversal().V(a, b).hasLabel("A");`
This query should return the vertex a only, but delivers both a and b.

This issue can be reproduced using the following test case:

```
@Test
public void testHasLabelWithIDs() {
        Vertex a = sqlgGraph.addVertex("A");
        Vertex b = sqlgGraph.addVertex("B");
    
        GraphTraversal<Vertex, Vertex> t = sqlgGraph.traversal().V(a, b).hasLabel("A");
    
        assertTrue(t.hasNext());
        Vertex v = t.next();
        assertEquals(a, v);
        boolean hasNext = t.hasNext();
        if (hasNext) {
            fail(t.next().toString());
        }
}
```

**Comment by pietermartin** [comment]
This has been fixed on the `optionalWithOrder` branch.
It is deployed in maven central as 1.4.0-SNAPSHOT
