### ISSUE TITLE
Multiple hasLabel() conditions give wrong results.

### ISSUE THREAD

**Issue by LotharGrabowsky** [pietermartin/sqlg#220]
Assume a vertex a with label A and a vertex b with label B. Now we drive a query with two hasLabel conditions, e.g. `sqlgGraph.traversal().V().hasLabel("A").hasLabel("B");`

This query should deliver an empty result, but delivers both a and b.

This issue can be reproduced using the following test case:

```
    @Test
    public void testMultipleHasLabels() {
        sqlgGraph.addVertex("A");
        sqlgGraph.addVertex("B");

        GraphTraversal<Vertex, Vertex> t = sqlgGraph.traversal().V().hasLabel("A").hasLabel("B");

        String msg = null;
        boolean hasNext = t.hasNext();
        if (hasNext) {
            msg = t.next().toString();
            hasNext = t.hasNext();
            if (hasNext) {
                msg += ", " + t.next().toString();
            }
        }
        assertNull(msg);
    }
```

**Comment by pietermartin** [comment]
This has been fixed on the `optionalWithOrder` branch.
It is deployed in maven central as 1.4.0-SNAPSHOT

**Comment by LotharGrabowsky** [comment]
Perfect. Almost all issues I experienced with the master are gone. Only one is remaining. Will create an issue when I have prepared a test case.
