### ISSUE TITLE
PostgreSQL edge label length limit

### ISSUE THREAD

**Issue by MartinBrugnara** [pietermartin/sqlg#222]
I got edges with labels longer than 63 charters, and it seams `sqlg` creates a table for each ones...
There is any workaround I can use? (I would really like to avoid [hacking](https://stackoverflow.com/questions/8213127/maximum-characters-in-labels-table-names-columns-etc#8218026) PG sources).

Thanks,
Martin

**Comment by pietermartin** [comment]
What do you mean 'creates a table for each ones'?

It is suppose to throw an Exception
```
    @Test
    public void testLabelLength() {
        Vertex v1 = this.sqlgGraph.addVertex(T.label, "A");
        Vertex v2 = this.sqlgGraph.addVertex(T.label, "B");
        v1.addEdge("A12345678901234567890123456789012345678901234567890123456789halo", v2);
        this.sqlgGraph.tx().commit();
    }
```

throws
```
java.lang.IllegalStateException: Postgres table names must be 63 characters or less! Given table name is E_A12345678901234567890123456789012345678901234567890123456789halo

	at org.umlg.sqlg.sql.dialect.PostgresDialect.assertTableName(PostgresDialect.java:137)
	at org.umlg.sqlg.structure.EdgeLabel.createEdgeTable(EdgeLabel.java:110)
	at org.umlg.sqlg.structure.EdgeLabel.createEdgeLabel(EdgeLabel.java:46)
```

Sqlg does not have a solution for this at present.
Suppose we could do some kind of mapping.

**Comment by MartinBrugnara** [comment]
Sorry for my poor english.
Given the error I assumed sqlg creates for each edge label a table with the label values as name.

Yes, your test reproduces my problem. 
What do you suggest me to do?

**Comment by pietermartin** [comment]
I suggest you shorten the name. :-(
Sqlg could support a column alias feature but it obfuscates the database. One of the things I like about Sqlg that the db is easy to read with normal sql tools. If Sqlg had to alias it then regular folk accessing the db with sql would not know the column name.

**Comment by MartinBrugnara** [comment]
> I suggest you shorten the name. :-( 

Well, then I will shorten.

> Sqlg could support a column alias feature but it obfuscates the database. One of the things I like about Sqlg that the db is easy to read with normal sql tools. If Sqlg had to alias it then regular folk accessing the db with sql would not know the column name.

Are we talking about `table names` or `column names`? Does this choices affects also the range of admissible charters for the edge labels?

I really like your point of view, but considering the role of labels in graphs, I would suggest to consider providing also a transparent mapping feature, disabled by default, that the user can activate when needed. =)

**Comment by pietermartin** [comment]
Sorry I am talking about about labels however the same limit applies to column names.
I'll create an issue for this, but for now its a low priority.

**Comment by MartinBrugnara** [comment]
I totally understand.
Until then, is there a warning somewhere in the doc? ;)

Thank you for the support,
Martin

**Comment by pietermartin** [comment]
Hmm, doubt it, I'll add one in, thanks
