### ISSUE TITLE
PostgreSQL "cached plan must not change result type" while loading.

### ISSUE THREAD

**Issue by MartinBrugnara** [pietermartin/sqlg#223]
I am trying to load a dataset with the following code but I get `ERROR: cached plan must not change result type`. Maybe be this related to #140 #116? 
Could be something I am doing or a bug?

```groovy
final InputStream is = new FileInputStream(DATASET)
final GraphSONMapper mapper = graph.io(IoCore.graphson()).mapper().create()
graph.io(IoCore.graphson()).reader().create().readGraph(is, graph)
```

Thanks,
Martin

**Comment by pietermartin** [comment]
Yes looks rather similar, I'll try duplicate it with your example.

**Comment by MartinBrugnara** [comment]
Please let me know if can help in anyway, like providing a sample.

**Comment by pietermartin** [comment]
Yes thanks, a sample will be nice.

**Comment by MartinBrugnara** [comment]
Here it comes: [ldbc](https://drive.google.com/open?id=0BwX66B9ISrt4VU9JZGo5anFyVVU).

**Comment by pietermartin** [comment]
Say, what format is that file? Does not look like TinkerPop Graphson to me.

**Comment by MartinBrugnara** [comment]
It's GraphSON Version 2.0, it is compatible with both thinkerpop 2 and thinkerpop 3.

**Comment by pietermartin** [comment]
Well it looks different to me.
The TinkerPop parser crashes in my test as the json is not valid.
I tried loading it with TinkerGraph but that crashes with the same error.

```
        try (final InputStream stream = AbstractGremlinTest.class.getResourceAsStream("/ldbc.json")) {
            this.sqlgGraph.io(IoCore.graphson()).reader().create().readGraph(stream, this.sqlgGraph);
        }
```
I tried with `.unwrapAdjacencyList(true)` also but same issue.

I am getting,

```

java.lang.IllegalArgumentException: Property value can not be null

	at org.apache.tinkerpop.gremlin.structure.Property$Exceptions.propertyValueCanNotBeNull(Property.java:143)
	at org.apache.tinkerpop.gremlin.structure.util.ElementHelper.legalPropertyKeyValueArray(ElementHelper.java:121)
	at org.apache.tinkerpop.gremlin.structure.util.star.StarGraph.addVertex(StarGraph.java:98)
```

This is because it can not find the `id` property, but in general the json looks different to the various `tinkerpop-modern.json` in the TinkerPop project.

The same code works fine with tinkerpop-modern.json.

BTW which version of Sqlg are you working on?
Can you load the above file with TinkerGraph?

**Comment by MartinBrugnara** [comment]
I am positive about the file format: 
* I have already loaded other datasets (with the very same format) with sqlg.
* I have loaded that dataset with TinkerGraph and others dbs.

For you convenience, I posted here the relevant piece of my setup: [docker sqlg](https://pastebin.com/wUZXB81p).
SQLg is installed as: `:install org.umlg sqlg-postgres 1.3.3`
and activated as: 

```
:plugin use sqlg.postgres
:plugin use tinkerpop.sugar
```

Alternatively, you should be able to load it from java with:
```
r = LegacyGraphSONReader.build().create()
r.readGraph(new FileInputStream(DATASET), graph)
```

**Comment by MartinBrugnara** [comment]
@pietermartin I was just thinking, could it be related to the file type inference?

**Comment by pietermartin** [comment]
Ah, I'll try this evening with the legacy reader. Hopefully I can duplicate the exception.

**Comment by pietermartin** [comment]
Ok, using legacy loader I can duplicate the exception.
Unfortunately I don't understand why its happening.
Its happening on
```
INSERT INTO "public"."V_vertex" DEFAULT VALUES;
```
Now this does not really need to be a prepared statement. However every ddl statement calls `DEALLOCATE ALL` which is suppose to prevent `ERROR: cached plan must not change result type` exception from happening.

I want to investigate more before just changing the sql to not use a prepared statement.

In the mean time you can try,
```
    @Test
    public void testGithub223() throws IOException {
        this.sqlgGraph.tx().normalBatchModeOn();
        LegacyGraphSONReader r = LegacyGraphSONReader.build().batchSize(2_000_000).create();
        try (final InputStream stream = AbstractGremlinTest.class.getResourceAsStream("/ldbc.json")) {
            r.readGraph(stream, this.sqlgGraph);
        }
        this.sqlgGraph.tx().commit();
    }
```
In batch mode the error won't happen as it uses the `COPY` command. Its a lot faster also. About 22 seconds on my machine.

**Comment by pietermartin** [comment]
Another way that does not rely on Sqlg specific features.
Creating the vertex upfront removes the schema changes that cause the prepared statement cache error.
```
    @Test
    public void testGithub223() throws IOException {
        Vertex tmp = this.sqlgGraph.addVertex(
                "birthday",  "text",
                "lastName", "text",
                "firstName", "text",
                "gender", "text",
                "iid", "text",
                "browserUsed", "text",
                "locationIP", "text",
                "language", "text",
                "oid", "integer",
                "label", "text",
                "creationDate", "text",
                "email", "text",
                "imageFile", "text",
                "length", "text",
                "content", "text",
                "name", "text",
                "url", "text",
                "title", "text",
                "type", "text");
        tmp.remove();
        LegacyGraphSONReader r = LegacyGraphSONReader.build().create();
        try (final InputStream stream = AbstractGremlinTest.class.getResourceAsStream("/ldbc.json")) {
            r.readGraph(stream, this.sqlgGraph);
        }
        this.sqlgGraph.tx().commit();
    }

```

**Comment by pietermartin** [comment]
Ok, think I get whats going on.
After a ddl statement I execute `DEALLOCATE ALL` but it only deallocates the specific session/connection on the server.
Later another connection comes out of the pool which has previously prepared a statement that the ddl touched. This connection having been pooled has not been deallocated and throws the exception.

Trying a solutions with hooks into the C3PO pool to deallocate all connections.

**Comment by MartinBrugnara** [comment]
I didn't dig deep enough to help you with the connection pooling. 
But I am happy to inform you that the batch loading works great as work around, and that I am able to load the datasets.

**Comment by pietermartin** [comment]
Ok the best solution I have is to reset the connection pool on a ddl statement. This will close the connections. Postgres server side prepared statements are per session/connection so the cached plan will be cleared.
This does not completely make the problem go away as some active connections might still execute a prepared statement that now is no longer valid. We'll just have to live with that unless someone has an idea as to solving this.

`SqlDataSource` now has a method `softResetPool` which for the C3PO pool calls `softResetAllUsers`

@metlos Do you have any idea how we can make this, a custom connection pool call possible for the `JNDIDataSource`?

**Comment by pietermartin** [comment]
Going to close this for now. If containerized folk experience this then we can look at how to solve it for them.

**Comment by metlos** [comment]
The situation with JNDIDatasource is IMHO problematic, because we don't know what we're getting from JNDI - we assume it to be a DataSource implementation, but that's it.

We could try to see if the data source is a ConnectionPoolDataSource and try to register a callback to do something on an error of a statement (ConnectionPoolDataSource.getPooledConnection().addStatementEventListener()) but I'm not sure it would be possible to solve this situation completely using that approach...
