### ISSUE TITLE
Would love to see support for Impala/Kudu

### ISSUE THREAD

**Issue by kladkogex** [pietermartin/sqlg#225]
Would be fantastic to have support for Impala/Kudu (for analytic queries)

**Comment by pietermartin** [comment]
I don't actually understand how it would work though.
Sqlg only implements OLTP TinkerPop. OLAP TinkerPop's traversals are per 'star graph' (vertex plus incident edges), so it misses Sqlg's optimizations (chained joins) which in turn will probably miss Impala's optimizations.
Else its OLTP but traversals are wrapped up in a `Future`?

**Comment by pietermartin** [comment]
Closing this, afraid I do not want to suffer Hadoop's complexities and pain.
I'd be happy to support and work with someone who feels like doing this.
