### ISSUE TITLE
PostgreSQL Driver name

### ISSUE THREAD

**Issue by jgustie** [pietermartin/sqlg#229]
Currently the `PostgresPlugin#getDriverFor` method returns the string value `"org.postgresql.xa.PGXADataSource"`; this value is passed into the `com.mchange.v2.c3p0.ComboPooledDataSource#setDriverClass` method. I suspect this is incorrect since `PGXADataSource` is not an instance of `java.sql.Driver`.

It looks like from there C3P0 does a `Class#forName` on the data source class name, that class references the `org.postgresql.Driver` class which causes it to be loaded and made available to the `java.sql.DriverManager`. Since `ComboPooledDataSource.setForceUseNamedDriverClass(true)` is not called, no attempt is ever made to instantiate a `PGXADataSource` (the `driver` value on the factory setup method is ignored) and the `DriverManager` is consulted instead (which recognizes the connection URL and produces the roughly expected results).

I'm not sure what the intent was, but at the very least I suspect the `PostgresPlugin` should probably return `"org.postgresql.Driver"` and `ComboPooledDataSource.setForceUsedNamedDriver(true)` should be called to ensure consistency.

**Comment by pietermartin** [comment]
Oy, not sure why its there. Probably copy pasted and example and it worked. Its not because of any XA behavior.

**Comment by pietermartin** [comment]
Actually perhaps @metlos knows if its a requirement for Jboss or other container managed resource pools.
