### ISSUE TITLE
Null Pointer Exception on Adding a vertex with larger number of columns

### ISSUE THREAD

**Issue by ghost** [pietermartin/sqlg#233]
When clearing a table with previously populated columns and then adding a new vertex with more columns, a null pointer exception is thrown. Sample code below:

SqlgGraph sqlgGraph = UMLG.get().getUnderlyingGraph();

        //Create Schema
        Topology topology = sqlgGraph.getTopology();
        topology.ensureSchemaExist("TEST");

        LinkedHashMap<String, Object> columns = new LinkedHashMap<>();
        columns.put("Test1", "");
        columns.put("Test2", "");

        //Add a vertex and remove to create columns
        Vertex v = sqlgGraph.addVertex("TEST" + "." + "TEST_Table", columns);
        v.remove();
        sqlgGraph.tx().commit();

        columns = new LinkedHashMap<>();
        columns.put("Test1", "T1");
        columns.put("Test2", "T2");

        //Add the data
        Vertex vv = sqlgGraph.addVertex("TEST" + "." + "TEST_Table", columns);
        sqlgGraph.tx().commit();

        //Simulating second load
        //Remove the whole table label
        Optional<VertexLabel> tableVertexLabel = sqlgGraph.getTopology().getVertexLabel("TEST", "TEST_Table");
        if (tableVertexLabel.isPresent()) {
            tableVertexLabel.get().remove(false);
        }

        columns = new LinkedHashMap<>();
        columns.put("Test1", "");
        columns.put("Test2", "");
        columns.put("Test3", "");

        //Add a vertex with more columns than previously had
        v = sqlgGraph.addVertex("TEST" + "." + "TEST_Table", columns);
        v.remove();
        sqlgGraph.tx().commit();

        //break

**Comment by GregAbbott** [comment]
Deleted old profile, new one for reference
