### ISSUE TITLE
Have a SQL Predicate?

### ISSUE THREAD

**Issue by JPMoresmau** [pietermartin/sqlg#236]
Would it be a good idea to have a SQL Predicate that could take arbitrary SQL that would find its way into the where clause of the query?
We have the case where we want to do a traversal comparing two properties of the same vertex, and it's very cumbersome to express, and very slow compared to direct sql:

```
g.traversal().V().hasLabel(label).as("a", "b").select("a", "b").by("created").by("modified').where("a", P.lte("b"))
```
While something like
```
g.traversal().V().hasLabel(label).where(SQL("created<modified"))
```

Would be much faster and easier to write.

I suppose it could wreak havoc with all the aliasing we're doing?

**Comment by pietermartin** [comment]
Yeah, thing is there are loads of scenarios where SQL is simply better. In particular SQL is in a way more NoSql schema-less than gremlin as it can do random joins (virtual edges). Perhaps we should think of a way to execute pure slightly special SQL that returns vertices? No sure if this is even possible.

That said apart from the aliasing problem doing it for the `where` step is good. Gremlin is not so good at nested chained `or` and `and` clauses in the where clause either. Pushing predicates down to the db in general is a win.

**Comment by pietermartin** [comment]
My comment about gremlin not being good at chained `or` and `and` is incorrect. The `OrStep` and `AndStep` can do it just fine.

Regarding `g.traversal().V().hasLabel(label).where(SQL("created<modified"))` what we can perhaps instead do is something like,

`g.traversal().V().hasLabel(label).where(SQL("created", "modified", Compare.lt))`
`g.traversal().V().hasLabel(label).where(SQL("created", "modified", (a,b) -> return "a < b" ))`

This way we will not have the aliasing problem.
There might be a sql injection security issue with the second lambda option?

**Comment by JPMoresmau** [comment]
Could you have a look at my branch feature/sql_predicate. Is that ok? I've created a subclass of P to use in has clauses, like that: `.has("score",propertyRef(Compare.eq, "experience"))` (which becomes schema.table.score=schema.table.experience). Seems to work a charm for the simple tests I've created, not sure what other traversals I need to test.

**Comment by pietermartin** [comment]
Sure I'll have a look, thanks. Do you need it on the master branch? The merges to tp3.3.0 are becoming to conflicted for git to handle so am having to manually merge. It be great if you can target tp3.3.0 else its fine and I'll merge. tp3.0.0 is very close to done, tonight or tomorrow, however as the changes are significant it needs some more testing including on my work systems before being ready for a release.

**Comment by JPMoresmau** [comment]
For the moment it's on master but the changes are small, I could probably try to do them on top of tp3.3.0 too.

**Comment by pietermartin** [comment]
Ok thanks

**Comment by pietermartin** [comment]
Looks good to me, fits nice and simple in the current way of doing things.
You can send the PR to master and I'll merge it into tp3.3.0

**Comment by pietermartin** [comment]
Closed by https://github.com/pietermartin/sqlg/pull/255
