### ISSUE TITLE
Feature Request: Vertica Database dialect, or dialect writing documentation/guide?

### ISSUE THREAD

**Issue by mcampbell** [pietermartin/sqlg#241]
I see that the Vertica Database (https://www.vertica.com/) is not currently supported.

Is there any documentation on how one might go about writing a dialect for a currently unsupported database?

**Comment by pietermartin** [comment]
No unfortunately the docs are weak. As always I plan to update/improve them after releasing Sqlg on TinkerPop 3.3.0.

The main thing to do is to implement `org.umlg.sqlg.sql.dialect.SqlDialect` for Vertica.
There are quite a few dialects to use as examples.

I'd start by copying a maven module, say `HSQLDB` or `Postgresql`, change the `SqlgPlugin` service to work with Vertica, start running the test and fix things along the way.

One of the first things to fix will be to change `SqlgDialect.sqlgTopologyCreationScripts` as that creates Sqlg's meta data schema object. From there its changing sql fragments where the default does not work. Generally a basic dialect can be up and running quite fast. Supporting custom batch modes is normally where things are harder.

**Comment by mcampbell** [comment]
Thanks Pieter.  Will let you know if we have any issues here.
