### ISSUE TITLE
Optimize PropertiesStep when used inside a TraversalFilterStep or NotStep

### ISSUE THREAD

**Issue by jgustie** [pietermartin/sqlg#250]
This enhancement would allow `has(property)` and `hasNot(property)` to generate `IS NOT NULL` or `IS NULL` SQL queries. If there is another way to do that, I would be happy to use that as an alternative (I tried `P.eq(null)` but that gives an NPE in `PropertyType.from`).

**Comment by pietermartin** [comment]
I am almost done with the `DropStep` after that its this issue then the SQL predicate and then a release if all is well.

**Comment by JPMoresmau** [comment]
I have a fix for this issue, will issue PR in a while. However, I have an unrelated issue on TestGremlinCompileWhereLocalDate (Postgres issue, using 9.6)

**Comment by JPMoresmau** [comment]
There are a few TestGremlinCompile* tests not in AllTests, is that normal? Are they obsolete?

**Comment by pietermartin** [comment]
No not really, which ones? I am on tp3.3.0 branch now and most seem there.

**Comment by pietermartin** [comment]
hmm, I see so ja, not sure how/why that happened.

**Comment by JPMoresmau** [comment]
TestGremlinCompileGraphV.class,
     TestGremlinCompileVertexStep.class,
     TestGremlinCompileWhereLocalDate.class,

seem to be missing in master

**Comment by pietermartin** [comment]
Ok we can put them back in if they pass. I'll test them on all the other dialects.

**Comment by pietermartin** [comment]
The `has("property")` optimization is not taking labels into account.
`g.V().has("name").as("a").select("a")` fails

**Comment by JPMoresmau** [comment]
Sorry, I saw the code and I thought "I need to handle the labels too" and then I forgot. These few lines maybe should be factored in a method. Thanks!
