### ISSUE TITLE
has not working for properties with more that one column

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#253]
Period/Duration/ZonedDateTime needs attention when generating the where clause.

**Comment by pietermartin** [comment]
I see there is a commented out section in BaseStrategy that skips the optimization for ZonedDateTime,Period and Duration.
Need to comment it back in or better support the fields in the where clause.

**Comment by JPMoresmau** [comment]
Test pass (changing the number of steps after resolution) if I uncomment the optimization. I'd say keeping the SQL would be quite difficult, for example to compare 2 durations to see if one is greater than another, you need to compare the seconds, if equals you need to compare the nanos... I can submit a PR with the unoptimisation reenable, and we add the optimisation as another issue?

**Comment by pietermartin** [comment]
Yeah, I also had a look and came to the same concolusion.
Thanks
