### ISSUE TITLE
Add partitioning support

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#256]
Postgresql 10 has greatly improved partition support.
Add this functionality to Sqlg's `VertexLabel` and `EdgeLabel` topology creation.

**Comment by mdavis7771** [comment]
I'd also suggest ensuring support for other extensions that provide this partitioning value such as citus, or timescaledb extension support if the graph has timestamps involved.  I have found timescaledb in my testing to greatly outperform postgres10 partition because it is "automanaged" and the ondisk storage is optimized. Whereas with postgres10, you need partman or another extension and lots of config to get value.

**Comment by pietermartin** [comment]
I have not heard about `timescaledb` I'll have a look at it. `Citus` is on the //TODO list although my understanding of it is that `sharding` does not compete with `partitioning`. Individual shards can still be further partitionioned.

**Comment by pietermartin** [comment]
For now I am implementing native Postgresql 10 partitioning. Partly because it is "native" and because I can not tell if `Citusdb` will work with `Timescaledb`. Extensions on top of extensions seems messy.

As things stand now the api is as follows,

```
Schema testSchema = this.sqlgGraph.getTopology().ensureSchemaExist("test");
VertexLabel partitionedVertexLabel = testSchema.ensurePartitionedVertexLabelExist(
    "Measurement", 
    new HashMap<String, PropertyType>() {{
        put("date", PropertyType.LOCALDATE);
        put("temp", PropertyType.INTEGER);
    }},
    PartitionType.RANGE,
    "date"
);
partitionedVertexLabel.ensurePartitionExists("measurement1", "'2016-07-01'", "'2016-08-01'");
partitionedVertexLabel.ensurePartitionExists("measurement2", "'2016-08-01'", "'2016-09-01'");
this.sqlgGraph.tx().commit();

LocalDate localDate1 = LocalDate.of(2016, 7, 1);
this.sqlgGraph.addVertex(T.label, "test.Measurement", "date", localDate1);
LocalDate localDate2 = LocalDate.of(2016, 8, 1);
this.sqlgGraph.addVertex(T.label, "test.Measurement", "date", localDate2);
this.sqlgGraph.tx().commit();

Assert.assertEquals(2, this.sqlgGraph.traversal().V().hasLabel("test.Measurement").count().next(), 0);
Assert.assertEquals(1, this.sqlgGraph.traversal().V().hasLabel("test.Measurement").has("date", localDate1).count().next(), 0);
Assert.assertEquals(1, this.sqlgGraph.traversal().V().hasLabel("test.Measurement").has("date", localDate2).count().next(), 0);
```

Vertices and Edges can be partitioned. It will however be up to the user to put in the appropriate `has` clauses for the partitions to be used.

**Comment by mdavis7771** [comment]
Great! I will take a look at this during the week!

**Comment by pietermartin** [comment]
To check it out look at the `partition` branch. `TestPartition` and `TestPartitionMultipleGraphs` have tests to see the implementation.
Both VertexLabel and EdgeLabel support partitioning.
I still need to implement indexing on partitioned tables. This includes putting indexes on the edge tables' foreign keys (not proper foreign keys as they are not supported on partitioned tables) to the in and out vertex tables.

For now there is no auto management (adding and removing) of partitions. I plan however for the indexes to be quasi auto added. The index will only be manually added to the main table and when partitions are created the index will be added without the need to specify it.

**Comment by mdavis7771** [comment]
@pietermartin I use pg_partman (https://github.com/keithf4/pg_partman) for automatic partition management, might be something to look into. 

Also, per your statement of "Vertices and Edges can be partitioned. It will however be up to the user to put in the appropriate has clauses for the partitions to be used." with timescaledb, you can create a virtual "hypertable" which automates that all for you. It is one of the reasons I use timescaledb: simple and automatic partition management in addition to efficient disk storage.

Can't wait to see how my graph workloads work on this combined setup.

**Comment by pietermartin** [comment]
Last commit added support fo sub partitioning.
```
Schema publicSchema = this.sqlgGraph.getTopology().getPublicSchema();
VertexLabel a = publicSchema.ensurePartitionedVertexLabelExist(
        "A",
        new HashMap<String, PropertyType>() {{
            put("int1", PropertyType.INTEGER);
            put("int2", PropertyType.INTEGER);
            put("int3", PropertyType.INTEGER);
        }},
        PartitionType.RANGE,
        "int1");
Partition p1 = a.ensureRangePartitionWithSubPartitionExists("int1", "1", "5", PartitionType.RANGE, "int2");
Partition p2 = a.ensureRangePartitionWithSubPartitionExists("int2", "5", "10", PartitionType.RANGE, "int2");

Partition p1_1 = p1.ensureRangePartitionWithSubPartitionExists("int11", "1", "5", PartitionType.RANGE, "int3");
Partition p1_2 = p1.ensureRangePartitionWithSubPartitionExists("int12", "5", "10", PartitionType.RANGE, "int3");
Partition p2_1 = p2.ensureRangePartitionWithSubPartitionExists("int21", "1", "5", PartitionType.RANGE, "int3");
Partition p2_2 = p2.ensureRangePartitionWithSubPartitionExists("int22", "5", "10", PartitionType.RANGE, "int3");

p1_1.ensureRangePartitionExists("int111", "1", "5");
p1_1.ensureRangePartitionExists("int112", "5", "10");
p1_2.ensureRangePartitionExists("int121", "1", "5");
p1_2.ensureRangePartitionExists("int122", "5", "10");
p2_1.ensureRangePartitionExists("int211", "1", "5");
p2_1.ensureRangePartitionExists("int212", "5", "10");
p2_2.ensureRangePartitionExists("int221", "1", "5");
p2_2.ensureRangePartitionExists("int222", "5", "10");
this.sqlgGraph.tx().commit();

```
The api names are rather verbose but the first attempt at many overloaded `ensurePartitionExists` methods became too difficult to read.

Next up is managing indexes.

Regarding `pg_partman` it says in https://github.com/keithf4/pg_partman/blob/master/doc/pg_partman.md 

> For native partitioning, inserting data with no relevant child causes an error at this time. A default partition is in the works for a future major version of PostgreSQL (11+).

Looks to me that automatic partition creation is not yet supported for Postgresql 10

**Comment by pietermartin** [comment]
Latest commit adds support for indexes.
Indexes can not be added per partition. Instead they are added as per usual on the VertexLabel/EdgeLabel. The index will be added to all existing partitions and to all partitions as they are created.

**Comment by pietermartin** [comment]
Partitioning is pretty much done. Next up is Citus sharding.

**Comment by mdavis7771** [comment]
You are definitely correct that automated partitioning is not supported, however, in many use cases you know your partition structure ahead of time. For example, in my use case it is time series like data so I can pre-create partitions as jobs using month, day, or year time buckets.

I mentioned timescaledb as it does automatic partitioning and chunking within the OS using 1 or 2 dimensions (tme plus something else usually, E.g, location). These would be properties in the V_ tables of course but requires making the time column the PK, where as the existing PK in the V table would have to be indexed to be of use in lookups.

**Comment by pietermartin** [comment]
I'll look again sometime at timescaledb to see different it is from native and whats involved to support it.

**Comment by pietermartin** [comment]
Closing this ticket for now. I'll create a separate issue for adding Citus sharding support.

**Comment by pietermartin** [comment]
Somehow I missed the part where it says `sequences` are not a good idea for partitions. So partitioned tables in Sqlg should have user defined identifiers. i.e. no auto generated `ID` sequence.
This is being done at **https://github.com/pietermartin/sqlg/issues/274**.
The partition api needs to change to only be available if the user supplies the identifiers.

**Comment by pietermartin** [comment]
This is complete.
To create a partitioned table use the following api on `SqlgGraph`

```
        Schema publicSchema = this.sqlgGraph.getTopology().getPublicSchema();
        VertexLabel partitionedVertexLabel = publicSchema.ensurePartitionedVertexLabelExist("Cities",
                new LinkedHashMap<String, PropertyType>() {{
                    put("name", PropertyType.STRING);
                    put("population", PropertyType.LONG);
                }},
                ListOrderedSet.listOrderedSet(Collections.singletonList("name")),
                PartitionType.LIST,
                "name");
        partitionedVertexLabel.ensureListPartitionExists("Cities_a", "'London'");
        partitionedVertexLabel.ensureListPartitionExists("Cities_b", "'New York'");
        partitionedVertexLabel.ensureListPartitionExists("Cities_c", "'Paris'");
        partitionedVertexLabel.ensureListPartitionExists("Cities_d", "'Johannesburg'");
        this.sqlgGraph.tx().commit();

```
Partitioned tables must have user supplied identifiers.
Both LIST and RANGE partitions are supported.
Nested partitions is also supported.
