### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.apache.tinkerpop.gremlin.process.traversal.step.filter.CyclicPathStep

### ISSUE THREAD

**Issue by cloudhuang** [pietermartin/sqlg#258]
Add the dependencies, but encountered this error when test sqlg.

**Comment by pietermartin** [comment]
Can you give more details. Which version? When running what gremlin? A failing example will be great. 
Thanks

**Comment by pietermartin** [comment]
Can't duplicate.
