### ISSUE TITLE
Enable Travis CI on this repo

### ISSUE THREAD

**Issue by mbrukman** [pietermartin/sqlg#260]
There is a [`.travis.yml`](https://github.com/pietermartin/sqlg/blob/master/.travis.yml) file in the repo, but https://travis-ci.org/pietermartin/sqlg says the repo is not enabled. This step can only be done by the repo owner.

**Comment by pietermartin** [comment]
The test suite is too intense for Travis. Many databases, memory requirements, number of connections... I have not tried recently but gave up on getting the tests to pass on Travis.
I now run CI from on a home machine using Jetbrains' Teamcity. Its working fine except for every couple of days Teamcity becomes unavailable for a reason I have not yet investigated. I'll be home by tomorrow and restart Teamcity. The url is http://154.65.43.238:8111/viewType.html?buildTypeId=sqlg_Sqlg

I can enable Travis if you are interested in investigating the failures? Postgresql connections, java memory, MariaDB, MsSQLServer, etc

**Comment by pietermartin** [comment]
Closing this for now. TeamCity is behaving nicely. Feel free to open it again if you really want Travis.

**Comment by mbrukman** [comment]
No, wasn't specifically looking for Travis; just noticed that what the URL was pointing to was down and it was just an IP address, so figured since there's already a `.travis.yml` config, might as well switch to a free, fully-managed CI service, but per your explanation, sounds like Travis is not a good fit *and* you got it running again with Teamcity, so this is great.

Thanks for the explanation and making it run successfully again! Also, thanks for this awesome project.
