### ISSUE TITLE
Most likely an issue of postgres configuration, not sqlg (the oh no, I am new to this issue)

### ISSUE THREAD

**Issue by bshambaugh** [pietermartin/sqlg#277]
stack trace in Eclipse from running code::

12:09:43.401 [main] DEBUG org.umlg.sqlg.structure.SqlgGraph - Initializing Sqlg with PostgresDialect dialect
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException
	at org.umlg.sqlg.structure.SqlgGraph.<init>(SqlgGraph.java:237)
	at org.umlg.sqlg.structure.SqlgGraph.open(SqlgGraph.java:200)
	at numberone.two.main(two.java:27)
Caused by: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
	at org.umlg.sqlg.structure.SqlgDataSource.setupDataSource(SqlgDataSource.java:36)
	at org.umlg.sqlg.structure.SqlgGraph.<init>(SqlgGraph.java:230)
	... 2 more

CODE:::

public static void main(String[] args) {

        BaseConfiguration conf = new BaseConfiguration(); 
        conf.setProperty("jdbc.url", "jdbc:postgresql://localhost:5432/superhero");
    	conf.setProperty("jdbc.username", "postgres"); 
         // 	conf.setProperty("jdbc.password", "password");
        Graph g = SqlgGraph.open(conf);
}

Attempts with PostGres Are here::

http://raptorlicious.blogspot.com/2018/04/postgresql-weith-java-experiments.html

the next step I am going to try is a postgresql Java tutorial::
http://zetcode.com/java/postgresql/

**Comment by pietermartin** [comment]
Which version of Sqlg are you using as the line numbers are not matching up with what I have.
The latest version in maven central is 1.5.1

**Comment by bshambaugh** [comment]
psql (9.5.12)

**Comment by bshambaugh** [comment]
oops ...

**Comment by bshambaugh** [comment]
dependencies>
  
      
     <dependency>
       <groupId>org.apache.commons</groupId>
       <artifactId>commons-configuration2</artifactId>
       <version>2.0</version>
     </dependency>
     
     <dependency>
			<groupId>org.apache.tinkerpop</groupId>
			<artifactId>tinkergraph-gremlin</artifactId>
			<version>3.3.1</version>
		</dependency>
		
          <dependency>
             <groupId>org.apache.tinkerpop</groupId>
             <artifactId>gremlin-driver</artifactId>
             <version>3.3.1</version>
          </dependency>

		  <dependency>
              <groupId>org.umlg</groupId>
              <artifactId>sqlg-postgres</artifactId>
              <version>1.2.0</version>
          </dependency>
          
          <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.0</version>
          </dependency> 
  
  </dependencies>

**Comment by pietermartin** [comment]
You do not need all those dependencies.
Here is what you need for a minimal Sqlg project.

pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.umlg</groupId>
    <artifactId>sqlgtest</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>org.umlg</groupId>
            <artifactId>sqlg-postgres-dialect</artifactId>
            <version>1.5.1</version>
        </dependency>
    </dependencies>
</project>
```
java

```
package org;

import org.apache.commons.configuration.BaseConfiguration;
import org.apache.tinkerpop.gremlin.structure.Graph;
import org.apache.tinkerpop.gremlin.structure.T;
import org.apache.tinkerpop.gremlin.structure.Vertex;
import org.umlg.sqlg.structure.SqlgGraph;

import java.util.List;

public class TestMain {

    public static void main(String[] arg) {
        BaseConfiguration conf = new BaseConfiguration();
        conf.setProperty("jdbc.url", "jdbc:postgresql://localhost:5432/sqlgraphdb");
        conf.setProperty("jdbc.username", "postgres");
        conf.setProperty("jdbc.password", "xxx");
        Graph g = SqlgGraph.open(conf);
        g.addVertex(T.label, "A", "name", "halo");
        g.tx().commit();
        List<Vertex> vertices = g.traversal().V().hasLabel("A").toList();
        System.out.println(vertices.size());
        try {
            g.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

Sqlg will bring all it needs including TinkerPop and postgresql drivers.
