### ISSUE TITLE
Why are the edge tables missing values in postgresql?

### ISSUE THREAD

**Issue by bshambaugh** [pietermartin/sqlg#280]
Thanks Pieter for your help so far. Is there a way to begin troubleshooting this???

Here is the code:
https://gist.github.com/bshambaugh/5369a5dafd1f2991871a1969ad2b69e2

The stack trace does not help?

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
MLog initialization issue: slf4j found no binding or threatened to use its (dangerously silent) NOPLogger. We consider the slf4j library not found.
Apr 07, 2018 4:10:41 PM com.mchange.v2.log.MLog 
INFO: MLog clients using java 1.4+ standard logging.
Apr 07, 2018 4:10:41 PM com.mchange.v2.c3p0.C3P0Registry 
INFO: Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
Apr 07, 2018 4:10:41 PM com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource 
INFO: Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> z8kfsx9u18xn4y01cqc8pa|382db087, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.postgresql.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> true, identityToken -> z8kfsx9u18xn4y01cqc8pa|382db087, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> jdbc:postgresql://localhost:5432/sqlgraphdb, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 3600, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 100, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
[{peter=1855, vadas=1431, josh=3481, marko=1537}]

**Comment by bshambaugh** [comment]
Okay, this is strange. I set up my code more like your test suites in sqlg, and I reconnected to postgres, and now I see my tables for edges. I do not know what did it.

**Comment by pietermartin** [comment]
Sqlg tests drops the db before executing. This includes dropping the `sqlg_schema`.
Most of these questions are best asked on the forum https://groups.google.com/forum/#!forum/sqlg

**Comment by bshambaugh** [comment]
Interesting, Pieter. Thanks for your help!
