### ISSUE TITLE
Expose version via API and manifest

### ISSUE THREAD

**Issue by JPMoresmau** [pietermartin/sqlg#283]
The version of the library is in the file sqlg.application.properties and is read by SqlgStartupManager. It'd be good to have that version exposed via a public API (make getBuildVersion static and public) and also have the version in the manifest of the built jar (maven can do that for us easily). This can help downstream tools that include the library for debugging, etc.

**Comment by JPMoresmau** [comment]
I can work on that. Should I do that of master branch or of partitioning branch? Partitioning branch is now version 2.0, is there going to be a 1.6 version?

**Comment by pietermartin** [comment]
Do it on master, 2.0.0 might be a while still so I can do a 1.6.0 in the mean time.
