### ISSUE TITLE
Multi-column property types fail to bulk load if value is null

### ISSUE THREAD

**Issue by jgustie** [pietermartin/sqlg#294]
When the `PostgresDialect.valueToStringForBulkLoad` method receives a `null` value it blindly returns a single "batch null", it should also be adding a `COPY_COMMAND_DELIMITER` and additional batch null for each item in `PropertyType.getPostFixes`.

However, that does not solve the entire problem since `SqlBulkDialect.writeStreamingVertex` must infer the `PropertyType` from the value itself, when the value is `null` it guesses the type is `STRING` so `valueToStringForBulkLoad` would still do the wrong thing.

I'm not sure what the best fix is: I suspect it is just a matter of passing the property type information down to `writeStreamingVertex` so it doesn't need to guess. Another approach might be null markers (e.g. a "ZONEDDATETIME_NULL" constant to use instead of a real `null` so `PropertyType.from` could identify it), I suspect that would have more impact on the entire code base though.

**Comment by pietermartin** [comment]
Are you getting the error with single column fields, or only columns with postfixes?
Posting failing test will be best.
