### ISSUE TITLE
Batch loading fails on concurrent transactions

### ISSUE THREAD

**Issue by JPMoresmau** [pietermartin/sqlg#296]
I still need to write a test and really be sure but I'm getting issues when several concurrent transactions do import in batch mode. 
My gut feeling is that two transactions write vertices at the same time. Then at the end of flushVertexCache in PostgresDialect we get the current state of the sequence and we assume all vertex IDs are the consecutive values preceding this value. I think concurrent transactions may interleave these values, so we end up with edges (in flushEdgeCache) that use vertex ids that this transaction doesn't know, and we get a foreign key violation error. Which is arguable better than linking the wrong vertices together via edges.
The problem is random, of course.
A solution would be to lock the table during the duration of the copy + sequence check, if we're in distributed mode. Given that I run also into deadlocks (usually when the schema is modified as part of write operations) this may be dangerous.

**Comment by pietermartin** [comment]
That sequence check is bad.
Perhaps we can change that to use the `RETURNING` clause to get the `ID`s?

**Comment by JPMoresmau** [comment]
I don't think COPY handles returning generated IDs
