### ISSUE TITLE
Multiple select query returns no result in 2.0.0

### ISSUE THREAD

**Issue by JPMoresmau** [pietermartin/sqlg#308]
See full test case: https://github.com/JPMoresmau/sqlg/blob/df3d25344c07b59c7d011b392b25beaa78ad8d9c/sqlg-test/src/main/java/org/umlg/sqlg/test/complex/TestMultipleSelect.java

This query used to work in 1.5.3. Of course the query using project is much better, and works.

**Comment by pietermartin** [comment]
I have fixed this.
Added optimizing `PropertiesStep` in the `BaseStrategy` which allows the above query to be optimized.
Not completely happy though with the implementation, need to do tests for more scenarios.
