### ISSUE TITLE
is it allowed to call getSchema(null) in Topology class? 2.0.0

### ISSUE THREAD

**Issue by Easy65** [pietermartin/sqlg#312]
Hi Pieter,

we switched to 2.0.0 recently and we now get a NPE in getSchema which worked in the 1.5.3 branch.
We can fix that by using the public schema name here, but maybe it is allowed and should be fixed in 2.0.0?

The change in the method is this additional if:

`if (schema.equals(Schema.GLOBAL_UNIQUE_INDEX_SCHEMA)) {`

Regards,
Andreas

**Comment by pietermartin** [comment]
Just to check, are you calling `getSchema(null)` as in with the schema name as `null`?
If so did it return the `public` schema?

**Comment by Easy65** [comment]
Actually, the code is the following (with schema == null):

```
g.getTopology().getVertexLabel(schema, LABEL_SETTING).ifPresent(vl->{
    List<PropertyColumn> properties=Arrays.asList(vl.getProperty(PROPERTY_PATH).get());
    vl.ensureIndexExists(IndexType.UNIQUE, properties);
});
```
This internally calls getSchema(), which returned an empty Optional, I think.

**Comment by Easy65** [comment]
Yes, Jean-Philippe reported already a few other things and we switched to this version this week in development, so more people will use it now here.

**Comment by pietermartin** [comment]
Great tx
