### ISSUE TITLE
Parameterize values in SQLG query

### ISSUE THREAD

**Issue by vin0010** [pietermartin/sqlg#313]
Generated SQLG query has the ID inside the query instead of a parameter since it might lead to possible SQL injection.

org.umlg.sqlg.structure.SqlgGraph#elements(), line 1214
...and ended up in this database query:
SELECT * FROM "Schema"."Table" WHERE "ID" IN (10);

**Comment by JPMoresmau** [comment]
What query do you run?
Both
`Vertex v = this.sqlgGraph.traversal().V(marko.id()).next();`
And
`Iterator<Vertex> it=this.sqlgGraph.vertices(marko.id());`
generate
```
SELECT
	"public"."V_Person"."ID" AS "alias1",
	"public"."V_Person"."name" AS "alias2"
FROM
	"public"."V_Person"
WHERE
	( "public"."V_Person"."ID" = ?)
```

**Comment by JPMoresmau** [comment]
The line reported in SqlgGraph is not valid, maybe this was against 1.5.x and is not present anymore in 2.0

**Comment by pietermartin** [comment]
Closing this for now, please open it again if the issue persists.
