### ISSUE TITLE
Unexpected order in query result.

### ISSUE THREAD

**Issue by LotharGrabowsky** [pietermartin/sqlg#316]
There seems to be an influence of the path length in the result on a previous order step.
Assume the following data constellation.
Vertex a1 with a reference to b1
Vertex a2 with a reference to b2
Now executing a query
`GraphTraversal<Vertex, Path> t = sqlgGraph.traversal().V(a1, `a2).order().by("name").optional(__.out()).path();``
gives the expected result:
a1 -> b1
a2 -> b2

If removing b1 I would expect the result
a1
a2 -> b2
but the actual result is
a2 -> b2
a1

The issue can be reproduced with the following test case:

    public void testOrder() {

		Vertex a1 = sqlgGraph.addVertex(T.label, "A", "name", "a1");
    	Vertex a2 = sqlgGraph.addVertex(T.label, "A", "name", "a2");
    	Vertex b1 = sqlgGraph.addVertex(T.label, "B", "name", "b1");
    	Vertex b2 = sqlgGraph.addVertex(T.label, "B", "name", "b2");

    	a1.addEdge("e_a", b1);
    	a2.addEdge("e_a", b2);
 
   		GraphTraversal<Vertex, Path> t = sqlgGraph.traversal().V(a1, a2).order().by("name").optional(__.out()).path();
  		assertTrue(t.hasNext());
  		Path p = t.next();
  		assertEquals(2, p.size());
  		Vertex v1 = p.get(0);
  		assertEquals("a1", v1.property("name").value());
  		Vertex v2 = p.get(1);
  		assertEquals("b1", v2.property("name").value());
  		assertTrue(t.hasNext());
  		p = t.next();
  		assertEquals(2, p.size());
  		v1 = p.get(0);
  		assertEquals("a2", v1.property("name").value());
  		v2 = p.get(1);
  		assertEquals("b2", v2.property("name").value());
   		
   		b1.remove();
  		t = sqlgGraph.traversal().V(a2, a1).order().by("name").optional(__.out()).path();
  		assertTrue(t.hasNext());
  		p = t.next();
  		assertEquals(1, p.size());
  		v1 = p.get(0);
  		assertEquals("a1", v1.property("name").value());
  		assertTrue(t.hasNext());
  		p = t.next();
  		assertEquals(2, p.size());
  		v1 = p.get(0);
  		assertEquals("a2", v1.property("name").value());
  		v2 = p.get(1);
  		assertEquals("b2", v2.property("name").value());
	}

Btw, executing this test case against the TinkerGraph implementation delivers the expected result.

**Comment by JPMoresmau** [comment]
I had a look, and got lost... In this case we generate SQL with inner join so we get from postgres only the results for a2, then we get nothing for a1, so the order is wrong. If I transfer optionalLeftJoin from the schematabletree to the child schematabletree and generate left joins instead, everything fails with weird and wonderful errors (nullpointer, etc.).

**Comment by pietermartin** [comment]
`SqlgGraphStep` now includes a check to see if `order()` is before a step that requires a left join. In this case the ordering will happen in java memory and not on the db.
