### ISSUE TITLE
Add option to prevent on-demand schema creation

### ISSUE THREAD

**Issue by ktschmidt** [pietermartin/sqlg#334]
Sqlg normally creates/modifies the schema in the back-end database on demand, e.g. the first time a vertex or edge is created or as properties are created on them the first time.  This is convenient in many environments, but a production system likely wants to lock down the schema and not allow adhoc/rogue schema changes and/or doesn't want to risk the deadlocks that can occur when introducing DDL in the middle of a busy system doing a lot of DDL.

One way to address this would be to have a mode that can be enabled through configuration where adhoc/on-demand schema creation is not allowed and schema creation must be done using the Topology class(es).

Note that this approach would work well for our use case where we have a model definition in a JSON file that we read in and use the Topology classes to create the schema.  Any schema changes would first have us update our model definition and then use the Topology classes to effect the change.

**Comment by pietermartin** [comment]
Added a transaction scoped `unlockTopology`. This leaves the global lock locked and only allows the current thread to make changes.
