### ISSUE TITLE
Add ablility to specify 'NOT NULL' and DEFAULT value in the Database when creating a Vertex Schema in v2.0.

### ISSUE THREAD

**Issue by mog1919** [pietermartin/sqlg#342]
In version 1.5.x, it was possible to pass additional SQL that would be appended at column creation via the API

```public VertexLabel ensureVertexLabelExist(final String label, final Map<String, PropertyType> columns, Properties additional)```

by using the `additional` properties that could be passed in.  
For example, you could add "NOT NULL" or "DEFAULT ''" for adding null constrains or Default values to a column in the database.

In version 2.0.x, the `ensureVertxLabel` API no longer takes the additional Properties parameter, so it seems it is not possible to add custom SQL to the column creation.  Is there another way to do this, or can this functionality be added back in?

**Comment by pietermartin** [comment]
Afraid there is no way to do it currently, except maybe by issuing a custom sql command.
I definitely plan on adding first class support for `NOT NULL` but its not on the near horizon.
`DEFAULT` I was not thinking about but we might as well add it in there aswell.

**Comment by pietermartin** [comment]
This is being implemented on sqlg3 branch.
It includes `check` constraints and `multiplicity`

**Comment by pietermartin** [comment]
Done
