### ISSUE TITLE
NoSuchMethodError when creating a graph

### ISSUE THREAD

**Issue by chrishmorris** [pietermartin/sqlg#349]
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V

	at org.umlg.sqlg.structure.topology.Schema.createSqlgSchemaVertexLabel(Schema.java:439)
	at org.umlg.sqlg.structure.topology.Topology.<init>(Topology.java:399)
	at org.umlg.sqlg.structure.SqlgGraph.<init>(SqlgGraph.java:319)
	at org.umlg.sqlg.structure.SqlgGraph.open(SqlgGraph.java:248)
	at org.umlg.sqlg.structure.SqlgGraph.open(SqlgGraph.java:238)

The problem was resolved by removing some unneeded dependencies and:
```
rm -rf ~/.m2/repository/com/google/guava/
mvn compile
```
According to mvn dependency:tree, I'm actually getting guava version 23.4-jre. The[Sqlg pom](https://github.com/pietermartin/sqlg/blob/master/sqlg-core/pom.xml) does not specify a version:
```
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
```
I suggest specifying:
```
       
      <version>23.4-jre</version>
```

**Comment by pietermartin** [comment]
The root pom contains the version and it is `<version>23.4-jre</version>`
Not quite understanding why this is happening by you.
Which version are you working on?
How are you importing Sqlg into your project?

**Comment by pietermartin** [comment]
Closing this for now. Please open it again if the issue persists.
