### ISSUE TITLE
SQLG Documentation site down

### ISSUE THREAD

**Issue by Sandared** [pietermartin/sqlg#351]
Hi,

it seems the site sqlg.org is down. I get a connection_timed_out error.

Kind regards,
Thomas

**Comment by ssimeonov** [comment]
Still down.

**Comment by pietermartin** [comment]
Afraid there was a power outage for longer than my UPS can handle. I am only back home in 2 weeks time so for now it will be down till then.
You can checkout the code and go to `sqlg-doc` where all the ascii docs are.
Sorry, I need to get a server in the cloud somewhere.

**Comment by Sandared** [comment]
If you are generating a static website from your adoc file, then you could
simply host this site via GitHub pages :)


pietermartin <notifications@github.com> schrieb am Di., 25. Juni 2019,
17:58:

**Comment by baronwangr** [comment]
waiting...

**Comment by pietermartin** [comment]
I'll only be back, on the weekend, will get it back up then.

**Comment by Sandared** [comment]
So long the documentation can also be read here: https://github.com/pietermartin/sqlg/blob/master/sqlg-doc/docs/2.0.1/sqlg.adoc

**Comment by pietermartin** [comment]
Ok its up again, apologies.
