### ISSUE TITLE
Google Group not accessible

### ISSUE THREAD

**Issue by Sandared** [pietermartin/sqlg#354]
Hi,
I was trying to access the Google Group that is linked in the documentation, but only got a notification, stating that I'm not allowed to view this content.

I could not find a way to subscribe to the google group. 
Is this intended? Do I have to apply somewhere to be added to the forum?

Kind regards,
Thomas

**Comment by pietermartin** [comment]
Not sure, I just went there and refreshed the settings. Please try again.
Thanks
Pieter

**Comment by Sandared** [comment]
Still doesn't work for me. It says I don't have the permission to view this
Content. Error Nr. 418 :(

pietermartin <notifications@github.com> schrieb am So., 7. Juli 2019, 19:00:

**Comment by pietermartin** [comment]
Ok added more permissions. Looks like they recently changed stuff.
Try again please.
Thanks
Pieter

**Comment by Sandared** [comment]
Now I see an empty group and get the following notification:

This group either doesn't exist, or you don't have permission to access it.
If you're sure this group exists, contact the Owner of the group and ask
them to give you access.

pietermartin <notifications@github.com> schrieb am So., 7. Juli 2019, 19:24:

**Comment by pietermartin** [comment]
Ok, one more time, this time I tested it.
Thanks
Pieter

**Comment by Sandared** [comment]
Now it works! :)
Thank you so much for your help!

pietermartin <notifications@github.com> schrieb am So., 7. Juli 2019, 19:54:
