### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Sandared** [pietermartin/sqlg#355]
Hi,

I was wondering if there is a roadmap available for SQLg somewhere? 
I really love what you are doing and just would be interested in where you intend to go with this library.

Kind regards,
Thomas

**Comment by pietermartin** [comment]
Hi,

The roadmap is mostly the `enhancement` issues.
I can give you a brief roadmap that's on my mind.

1. Complete optimizing reducing steps. i.e. `min/max/sum/mean and group`
2. Upgrade latest tinkerpop.
3. Implement `rename` functionality. (I need this all the time at the day job)
4. Make a ui for Sqlg. To expose the graph's meta data that's in sqlg_schema allowing the user to edit manage the schema without having to write java.
5. This is getting far in to the future, but enrich the meta model. Add multiplicity constraints (one to many edges, default values, not null...)
...

Cheers

And whatever anyone from the community may convince me of.

**Comment by Sandared** [comment]
Thanks for the info :) 



Regarding 4: Maybe this helps: https://github.com/bricaud/graphexp

**Comment by pietermartin** [comment]
The idea is more to allow the user to see and edit the meta data. Similar to rdbms where you can see schemas, tables, columns, indexes... Secondly to execute gremlin statements. I am vaguely thinking about what type of query results can go into a grid. I am so used to sql results that seeing data in some quasie json formatted blob is like not seeing the data at all. So somehow support displaying gremlin results in a grid when possible else as one long string, and then maybe also displaying it with dots and stripes.

**Comment by Sandared** [comment]
ah ok, got it :)
