### ISSUE TITLE
String Ids

### ISSUE THREAD

**Issue by francisco-polaco** [pietermartin/sqlg#356]
Hi,

I was wondering what could be done to support string ids and what is the effort for it.
Could you comment on it?

Thanks,
Francisco

**Comment by pietermartin** [comment]
Sqlg does support string ids, sortof.
But you have to define the schema upfront then with, 
```
        VertexLabel aVertexLabel = this.sqlgGraph.getTopology().getPublicSchema().ensureVertexLabelExist(
                "A",
                new LinkedHashMap<String, PropertyType>() {{
                    put("stringId", PropertyType.varChar(100));
                    put("name", PropertyType.STRING);
                }},
                ListOrderedSet.listOrderedSet(Collections.singletonList("stringId"))
        );
```

This will create the table with `stringId` as the primary key.

Let me know if this will not work for your usecase.

**Comment by francisco-polaco** [comment]
I believe my problem is a little deeper.

I'm trying to emulate the nodes and edges tables using views of my own data. Since I cannot have "real" IDs, that is, primary keys. I'm trying to have some sort of concatenation of ids of the existing data. So I believe, it's more close to user defined IDs, but actual table IDs and not properties.

Do you believe that it's possible?

**Comment by pietermartin** [comment]
Not quite understanding, do you want Sqlg to work of existing tables?

**Comment by francisco-polaco** [comment]
Yes.

Currently, I want to create views on top of my records to "emulate" Sqlg's vertex and edge tables.

**Comment by pietermartin** [comment]
Ok, afraid that won't work, Sqlg hardcodes its database layout. There is no abstraction layer to decide naming conventions and what edge foreign keys should look like.

**Comment by francisco-polaco** [comment]
I'm currently surfing Sqlg code. To have an idea, how much effort would it take to make it work?
Would it require some major refactor?

**Comment by pietermartin** [comment]
Yeah a very major refactor. The biggest obstacle will be constructing the joins for the edges. There will need to be a whole abstraction layer to construct joins via arbitrary columns.

**Comment by francisco-polaco** [comment]
Could you point where are the join queries built, on the code?

**Comment by pietermartin** [comment]
Most of the logic is in `SchemaTableTree.constructSql(LinkedList<SchemaTableTree> distinctQueryStack)`
Quite a lot happens before that but that's where the queries get constructed.

**Comment by pietermartin** [comment]
Closing this for now, feel free to open it again.
