### ISSUE TITLE
Native UUID supports

### ISSUE THREAD

**Issue by alendit** [pietermartin/sqlg#361]
Some databases, i.e. Postgres have a native UUID type support. Sqlg known the property type `UUID`, too, but rather converts it to a string before inserting it into the database. Using a native type would have obvious performance benefits, equality  and comparison operations on UUID are vastly faster than they are on string on considerable length.

I propose to add a `supportsUUID` flag to the `SqlDialect` and change add a check in `setKeyValueAsParameter` for it. With some other minor changes we can get UUID support.

If this approach is fine, I'll send a PR.

**Comment by pietermartin** [comment]
Yeah sounds good, thanks.
