### ISSUE TITLE
Discrepancy in github Sqlg README.md file and Sqlg Documentation

### ISSUE THREAD

**Issue by reshmi-nair** [pietermartin/sqlg#371]
Hi,

README.md file does not mention about MySql Support, but in documentation it is mentioned the MySql is supported. Below are the snippets from README.md file and Documentation.

Please confirm whether Sqlg 2.0.0 Release supports MySql DB?

[README.md](https://github.com/pietermartin/sqlg/blob/2.0.0/README.md)
Sqlg is a implementation of Tinkerpop3 on a RDBMS. Currently H2, HSQLDB, Postgresql, MariaDB and MSSqlServer are supported.

[Sqlg Documentation](http://sqlg.org/docs/2.0.0-SNAPSHOT/)
Sqlg  is a implementation of Apache TinkerPop on a RDBMS. Currently Postgresql, HSQLDB, H2, MariaDB, MySQL and MSSqlServer are supported.

Thanks,

**Comment by pietermartin** [comment]
Yes it supports `MySql`, I'll change the readme.
Thanks

**Comment by pietermartin** [comment]
Fixed
