### ISSUE TITLE
Changing traversal from using not and has to hasNot results in incorrect result

### ISSUE THREAD

**Issue by ktschmidt** [pietermartin/sqlg#397]
Update:

All the below is accurate and is closer to what is actually being done, but further research shows the problem can be observed with something as simple as:

a1 = g.addV("A").property("startDate", 0).next();
a2 = g.addV("A").property("startDate", 0).property("endDate", 10L).next();

This works correctly (not and has):

g.V().hasLabel('A').has('startDate', P.lte(9)).or(__.not(__.has('endDate')), __.has('endDate', P.gt(9))).as("svc").select("svc").count();

This works correctly (hasNot):

g.V().hasLabel('A').has('startDate', P.lte(9)).or(__.hasNot('endDate'), __.has('endDate', P.gt(9))).as("svc").count();

This fails (hasNot with select):

g.V().hasLabel('A').has('startDate', P.lte(9)).or(__.hasNot('endDate'), __.has('endDate', P.gt(9))).as("svc").select("svc").count();

=====

I've been using the combination of not() and has() in a number of traversals, but upon having reports of some slow performance, I looked at the generated SQL and saw that what was being filtered did not end up in the SQL, instead the filtering seems to be done in code.

I discovered that when I instead used hasNot(), the filtering did get in the SQL resulting in better performance.  However, the result of the traversal has changed, specifically, it isn't returning any results.

Here is a simple example:

a1 = g.addV("A").property("startDate", 0).next();
a2 = g.addV("A").property("startDate", 0).property("endDate", 10L).next();
b1 = g.addV("B").property("startDate", 0).property("endDate", 10L).next();
b2 = g.addV("B").property("startDate", 0).next();
a1.addEdge("r", b1, "startDate", 0, "endDate", 10L);
a2.addEdge("r", b2, "startDate", 0);

Then using not and has:

g.V().hasLabel('A').has('startDate', P.lte(9)).or(__.not(__.has('endDate')), __.has('endDate', P.gt(9))).as("svc").outE('r').has('startDate', P.lte(9)).or(__.not(__.has('endDate')), __.has('endDate', P.gt(9))).inV().has('startDate', P.lte(9)).or(__.not(__.has('endDate')), __.has('endDate', P.gt(9))).select("svc").count();

This returns 2 as expected.  However, it does it with 3 SQL queries.  And you can see this if the traversal is profiled:

```
Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
SqlgGraphStep(vertex,[])                                               2           2           1.227     2.68
SqlgOrStepBarrier([[SqlgNotStepBarrier([[SqlgTr...                     2           2           1.560     3.41
  SqlgNotStepBarrier([[SqlgTraversalFilterStepB...                     1           1           1.148
    SqlgTraversalFilterStepBarrier([PropertiesS...                     1           1           0.247
      PropertiesStep([endDate],value)                                  1           1           0.081
  SqlgHasStep([endDate.gt(9)])                                         1           1           0.058
SqlgVertexStep                                                         2           2          36.290    79.32
SqlgOrStepBarrier([[SqlgNotStepBarrier([[SqlgTr...                     2           2           1.018     2.23
  SqlgNotStepBarrier([[SqlgTraversalFilterStepB...                     1           1           0.348
    SqlgTraversalFilterStepBarrier([PropertiesS...                     1           1           0.229
      PropertiesStep([endDate],value)                                  1           1           0.071
  SqlgHasStep([endDate.gt(9)])                                         1           1           0.043
SqlgVertexStep                                                         2           2           4.766    10.42
SqlgOrStepBarrier([[SqlgNotStepBarrier([[SqlgTr...                     2           2           0.776     1.70
  SqlgNotStepBarrier([[SqlgTraversalFilterStepB...                     1           1           0.245
    SqlgTraversalFilterStepBarrier([PropertiesS...                     1           1           0.136
      PropertiesStep([endDate],value)                                  1           1           0.044
  SqlgHasStep([endDate.gt(9)])                                         1           1           0.031
SelectOneStep(last,svc)                                                2           2           0.114     0.25
                                            >TOTAL                     -           -          45.754        -
```

Switching to use hasNot:

g.V().hasLabel('A').has('startDate', P.lte(9)).or(__.hasNot('endDate'), __.has('endDate', P.gt(9))).as("svc").outE('r').has('startDate', P.lte(9)).or(__.hasNot('endDate'), __.has('endDate', P.gt(9))).inV().has('startDate', P.lte(9)).or(__.hasNot('endDate'), __.has('endDate', P.gt(9))).select("svc").count();

This issues a single SQL query which is desired, but it returns 0 and not the correct 2.

Profiling this shows:

Step                                                               Count  Traversers       Time (ms)    % Dur
=============================================================================================================
SqlgGraphStep(vertex,[])                                               2           2          43.873    99.89
SelectOneStep(last,svc)                                                                        0.046     0.11
                                            >TOTAL                     -           -          43.919        -

This shows the SqlgGraphStep has the 2 results, but they aren't selected by the SelectOneStep.

So the SQL looks correct in this case, but the results don't make it through after that for some reason.

Doing the above with TinkerGraph does work and result both results in both cases.

I assume this is a bug so will open a ticket as well.

Note that having written all this, I then experimented with how much of the hasNot instance works, and discovered leaving off the final select("svc") works, and it is the addition of it that causes the issue.   This works and returns 2:

g.V().hasLabel('A').has('startDate', P.lte(9)).or(__.hasNot('endDate'), __.has('endDate', P.gt(9))).as("svc").outE('r').has('startDate', P.lte(9)).or(__.hasNot('endDate'), __.has('endDate', P.gt(9))).inV().has('startDate', P.lte(9)).or(__.hasNot('endDate'), __.has('endDate', P.gt(9))).count();

So the combination of hasNot and the select seems to cause the problem.

**Comment by pietermartin** [comment]
Fixed in branch `2020`. It has to do with the label being lost during the `ConnectiveStep` optimization.
