### ISSUE TITLE
Serializer problems

### ISSUE THREAD

**Issue by Ziang-Wang** [pietermartin/sqlg#458]
i install sqlg-postgres plugin into germlin server. 
through gremlin console remotely connect to server, i can add vertices and count vertices successfully. 
but when i use a visualizer called "gdoty" to remotely connect to server, i has some errors" Error during serialization: Serializer for type org.umlg.sqlg.structure.RecordId not found"

**Comment by pietermartin** [comment]
Do you have a link for gdoty? 
I will have a look later, though I am travelling a present.

**Comment by Ziang-Wang** [comment]
Have you made any progress. I'm looking for visualization software. Do you recommend one?

**Comment by pietermartin** [comment]
I can not recommend anything as I do not use any visualisation software.
Regarding `gdotv` you will have to show me more information? 
I suggest asking `gdotv` as I do not use `gdotv`.

**Comment by Ziang-Wang** [comment]
link for gdoty:&nbsp;https://gdotv.com/
thanks a lot!
Looking forward to your early reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pietermartin/sqlg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月4日(星期六) 下午3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pietermartin/sqlg] Serializer problems (Issue #458)





 
Do you have a link for gdoty?
 I will have a look later, though I am travelling a present.

**Comment by pietermartin** [comment]
Last I tried I was unable to install `gdotv` on my `arch` linux distro.
I'll try contact the author to see if there is a way other than a `.deb` file.

**Comment by pietermartin** [comment]
As I am not a user of `gdotv` I'll need someone else to investigate the issue and log an issue.
Closing it for now.
