### ISSUE TITLE
Where are the examples?

### ISSUE THREAD

**Issue by rhubarb** [pietermartin/sqlg#460]
There are a thorough set of tests which helps a lot, but a single code example would go a bit further.

**Comment by pietermartin** [comment]
Ok, just to make sure we are on the same page, you'd like a fuller example in the documentation somewhere.
i.e. Open a graph, create a vertex and edge, query it and close the graph?

**Comment by pietermartin** [comment]
Sqlg has thousands of tests, I'll need details if you want a specific example.
