### ISSUE TITLE
MySql and MariaDb support

### ISSUE THREAD

**Issue by dezmaeth** [pietermartin/sqlg#511]
Hi @pietermartin,

Firstly, thank you for your incredible work on SQLG. It's a fantastic tool, and its versatility is highly appreciated within the community.

I understand that support for MySQL and MariaDB was removed in the latest version due to time constraints. These databases are widely used, and their support is crucial for many of us.

I would like to offer help reintroduce MySQL and MariaDB compatibility to SQLG. I believe that with collaboration, we can restore this functionality and continue to improve the utility and reach of SQLG.

Please let me know how best I can assist with this. I am open to contributing through a pull request or collaborating in any other way that suits the project's needs. Your guidance and direction on how to proceed will be greatly appreciated.

Looking forward to your response.

Best regards,

**Comment by pietermartin** [comment]
Hi, sorry for the late reply, I am traveling at the moment.

Thanks for the offer to help restore MySQL and MariaDB. I am back in August and will contact you to see how we can collaborate on maintaining and improving the MySQL and MariaDB dialects.

Regards
Pieter

**Comment by pietermartin** [comment]
I added back support for `mariadb` and `mysql`.
@dezmaeth can you check this on your environment please.

Sqlg's tests are passing. Need to think of a way to execute TinkerPop's feature test suit. It requires multiple dbs which is not possible on mariadb/mysql without running multiple servers.

The work is on the `mariadb_mysql` branch.

**Comment by pietermartin** [comment]
`MariaDB` and `Mysql` passes the test suites.

**Comment by dezmaeth** [comment]
awesome, i'll check it!

**Comment by pietermartin** [comment]
Merged this into master.
Closing the issue for now.
Please create new issues for any specific issues that arise.
