### ISSUE TITLE
Make SqlgGraph extensible

### ISSUE THREAD

**Issue by rhinoman** [pietermartin/sqlg#519]
I would like to subclass SqlgGraph in order to override a few methods (primarily I wish to override the `traversal()` method in order to return my own custom GraphTraversalSource class).

However, the use of private constructors make this difficult.  Would it be possible to add a public constructor so that SqlgGraph can be subclassed?

**Comment by pietermartin** [comment]
Done and deployed to maven snapshot, `3.1.2-SNAPSHOT`

**Comment by rhinoman** [comment]
Thank you!
