### ISSUE TITLE
Add update element.property(key, value) tests for all data types.

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#56]
The current test coverage for element.property(key, value) is weak.

**Comment by JPMoresmau** [comment]
I also see a todo on property(key), talking about "hidden". I see no differences between `internalGetProperties()` and `internalGetHiddens()`... 
Also, do you have specific tests that would be missing? More data types? Error conditions like invalid names and such?

**Comment by pietermartin** [comment]
I think I basically lost track of the hidden logic. That code is duplicated, for no good reason except that I am not fully aware of how I handle hiddens anymore. TinkerPop test suite test for it and it passes. Basically just need to reunderstand the code around hiddens.

The test coverage of element.property(key, value) does not cover all data types at present.
Batch mode is covered but not normal mode.
I do not expect issues but its good to ensure we test all data type's sql.

**Comment by JPMoresmau** [comment]
OK, started adding some tests at https://github.com/pietermartin/sqlg/compare/master...JPMoresmau:test/property?expand=1

**Comment by pietermartin** [comment]
Great, tx

**Comment by JPMoresmau** [comment]
There are still issues with time related data types, for example when we set one ZonedDateTime property we forget to set the zoneid column value. I also see issues where reading directly from the vertex we modified works, but reading via a traversal doesn't.

**Comment by pietermartin** [comment]
json is covered in the `TestJsonUpdate`
only Postgis data types needs update tests.
