### ISSUE TITLE
look at replacing hazelcast with rdbms notify and locking

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#58]
Replace Hazelcast's distributed lock by locking on the rdbms.
Use the rdbms's trigger/notify mechanism to update the schema cache

**Comment by pietermartin** [comment]
Some comments on this.

Since adding `TopologyManager` to store the topology in the graph itself there is some overlap between `TopologyManager` and `SchemaManager` 's responsibilities.

`SchemaManager` creates the schema and caches it. `TopologyManager` stores it in `sqlg_schema`
This issue is to remove Hazelcast from distributing the cache and make the cache itself more inline with the meta topology and to make it easier to extend with runtime requirements.

The idea is to make the SchemaManager more object orientated with smaller classes managing the schema creation and caching. Basically have a classes for Topology, Schema, VertexLabel, EdgeLabel, Property. These classes will manage the schema creation, sqlg_schema topology and local java cache.

After this further an mechanism must be worked out to make the meta data extensible.
There are many uses for storing meta data. 
* unique constraints
* special properties, i.e. 'className' per vertex label for OGM tools.
* caching, readOnly and on and on

The `removeHazelcast` branch contains the beginnings of all this.

**Comment by pietermartin** [comment]
Make the topology schema creation methods public to allow users to use this functionality.

**Comment by pietermartin** [comment]
@JPMoresmau 

I had a better look at what you have done in #105 
I implemented the semantics somewhat differently to you though.
`ensureSchemaExists("A") returns the `Schema` and it does so transactionally. i.e. if the schema "A" is created in the current not yet committed transaction then it will still return the to be committed Schema.

The same goes for any `ensure...` `ensureVertexLabel`, `ensureEdgeLabel`, `ensureVertexLabelProperty`...

Your implementation however returns false.

Do you forsee problems with the way I have done it?

**Comment by pietermartin** [comment]
The test you added look like this now
```
    @Test
    public void testEnsureSchema(){
    	Topology mgr=this.sqlgGraph.getTopology();
    	this.sqlgGraph.addVertex(T.label, "A.A");
    	this.sqlgGraph.tx().commit();

    	assertTrue(mgr.existSchema(this.sqlgGraph.getSqlDialect().getPublicSchema()));
    	assertTrue(mgr.existSchema("A"));
    	assertNotNull(mgr.ensureSchemaExist("A"));

    	assertFalse(mgr.existSchema("B"));
    	// false means didn't exist, //NOT RETURNING FALSE
    	assertNotNull(mgr.ensureSchemaExist("B"));
    	// not committed yet
    	assertTrue(mgr.existSchema("B"));
    	this.sqlgGraph.tx().commit();
    	assertTrue(mgr.existSchema("B"));

    }
```

**Comment by JPMoresmau** [comment]
My goal was to return something that tells me if there was a modification or not, to know if I have a DDL pending in the transaction, because then I may want to commit quickly. In my current use case it's not a problem, though. Maybe we should expose a method hasUncommitedSchemaChanges that looks if there are uncommitted schemas/tables, etc.

**Comment by pietermartin** [comment]
Ok, I'll look at adding that.
Regarding helping on removeHazelcast. I am hoping to complete it this week. I'll let you know and then if you can test it on your systems before I merge it in it will be great.
The postgres notify has worked well and the SchemaManager refactor is complete. All the tests are passing, just need to improve the caching (denormalized) the schema/topology maps as its kinda slow now having being normalized.

**Comment by JPMoresmau** [comment]
OK, great.

**Comment by pietermartin** [comment]
An update.
This is slipping as I'd like to implement indexes better.
Currently Sqlg only support an index on one property. rdbmses all support having a index on one or more properties so Sqlg should also support this.
As this affects the Sqlg's modelling of the topology in the sqlg_schema and this issue is making so many changes there it might as well be done now.

This means a new `Index` table will be created in `sqlg_schema`.
```
VertexLabel/EdgeLabel ----->----- 
         [1]                     |
          |                      |
          |                      |
        [0..*]                   |
       Index[0..*]---->---[1..*]Property
```

**Comment by pietermartin** [comment]
@JPMoresmau can you test this branch on your environment? I have started testing it at my work on our environments. If all goes well, I'd like to merge it into master soon.

**Comment by JPMoresmau** [comment]
@pietermartin , two API changes that impact us:
- `Sqlggraph.v(Object) -> Vertex` has been removed? There's `vertices` that return an iterator, maybe adding a single version vertex that returns null if nothing matches would be good.
- SchemaManager.getTopology.ensuresSchemaExists() returns a Schema, but I have no way to check if the schema was just created or existed before. We use other tables in a schema, so I would like to avoid a commit if there's no changes to commit. We had said maybe we could expose a method with the list of uncommited schemas, maybe?

Apart from that, all our tests in work still pass. I haven't looked into detail at all your changes and I'm travelling all week so I won't be available. But since things work, and 1.3.2 has been released so we could stay on that, I don't have any issues with you merging.

**Comment by pietermartin** [comment]
I'll put `SqlgGraph.v(object)`  back with a deprecation annotation.
There is `Topology.getUncommittedAllTables()` but yes I forgot about the `schema`

 I'll add a `uncommitted` boolean to Schema/VertexLabel/EdgeLabel/Property/Index so that you can tell on the returned object from the `ensureThisExists` methods.

**Comment by pietermartin** [comment]
This is done and in master, there are some intermittent failures and general performance optimizations needed, but they can get separate issues
