### ISSUE TITLE
Incorrect query generation

### ISSUE THREAD

**Issue by metlos** [pietermartin/sqlg#62]
Strange things happen when one combines multiple `out` hops with `or`. See the following test:
```java
    @Test
    public void testOrQuery() {
        Vertex a = sqlgGraph.addVertex(T.label, "a", "p", "a");
        Vertex b = sqlgGraph.addVertex(T.label, "b", "p", "b");
        Vertex c = sqlgGraph.addVertex(T.label, "c", "p", "c");

        a.addEdge("e", b, "p", "x");
        b.addEdge("e", c, "p", "y");

        //works
        Iterator<Vertex> results = gt.V().has("p", "b").outE("e")
                .or(__.has("p", "x"), __.has("p", "y")).inV().has("p", "c");
        Assert.assertEquals(c, results.next());

        //throws exception during query generation
        results = gt.V().has("p", "a").out("e").has("p", "b").outE("e")
                .or(__.has("p", "x"), __.has("p", "y")).inV().has("p", "c");
        Assert.assertEquals(c, results.next());
    }
```

Notice that the not working query merely starts from a different starting point and has one more `out("e").has("p", "b")` section.

Further more, when I remove the `or` section from the second query, it works, too.

**Comment by pietermartin** [comment]
The query generation is failing on a rather simple case of,
```
        Vertex a = sqlgGraph.addVertex(T.label, "A");
        Vertex b = sqlgGraph.addVertex(T.label, "B");
        Vertex c = sqlgGraph.addVertex(T.label, "C");
        a.addEdge("e", b);
        b.addEdge("e", c);
        sqlgGraph.tx().commit();
        Iterator<Edge> results = gt
                .V().hasLabel("A")
                .out("e")
                .inE("e");
```
The scenario occurs when the same edge label is used connecting different vertex labels and the query loops back onto itself.

So 'e' is used for 'A <-> B' and 'B <-> C' and the query goes out('e') and then inE('e').

**Comment by pietermartin** [comment]
Only generate sql select for the edge foreign key ids for the previous vertex label. Previously it generated sql for all edge foreign key ids.
