### ISSUE TITLE
searching for edges across schema fails

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#65]
The following test fails.
```
    @Test
    public void test() {
        Vertex a1 = this.sqlgGraph.addVertex(T.label, "A.A");
        Vertex b1 = this.sqlgGraph.addVertex(T.label, "B.B");
        a1.addEdge("eee", b1);
        this.sqlgGraph.tx().commit();
        assertEquals(1, this.sqlgGraph.traversal().E().hasLabel("eee").count().next().intValue());
    }
```
The edge table is created in schema 'A' but this information is not used when quering. Its defaulting to 'public'

**Comment by JPMoresmau** [comment]
I've fixed the bug, but it breaks another test, `TestSchema.testManySchemas`, where we tested:

 ```
Assert.assertEquals(0, this.sqlgGraph.traversal().E().has(T.label, "edge").count().next(), 0);
 Assert.assertEquals(100, this.sqlgGraph.traversal().E().has(T.label, "Schema0.edge").count().next(), 0);
```

Is it OK to change that test and hence change the behavior of the code?

**Comment by pietermartin** [comment]
Yeah its ok.

**Comment by JPMoresmau** [comment]
OK, do we really need that extra test class you've added? Shouldn't I just move the test class to TestSchema, since it's related to that behavior?

**Comment by pietermartin** [comment]
No we do not need it. Thanks
