### ISSUE TITLE
Could get smaller artifacts without gremlin-groovy

### ISSUE THREAD

**Issue by jotak** [pietermartin/sqlg#68]
I've found that we can noticeably reduce the size of the generated artifacts in the case where we don't use any of the provided _XXGremlinPlugin_. The reason is the dependency on _gremlin-groovy_ , which brings lot of other groovy/ivy-xx jars.

I've found that _sqlg-core_ currently has a dependency on _gremlin-groovy_ but it isn't actually used. Just _XXGremlinPlugin_ classes make use of it.

So I suggest a bit of refactoring in the dependencies and/or maven module to allow consumers to pick lighter artifacts.

For now in my application, I'm excluding _gremlin-groovy_ from the dependency on _sqlg-xx_, but this is neither a very elegant, nor durable solution: there's always a risk to miss a required dependency transitively brought by _gremlin-groovy_ (and actually, there's currently apache's commons-lang3 in that situation)

I'd be glad to do that little refactoring but would like to discuss how to proceed, if you're interested: move out gremlin plugin files to other maven modules? That would duplicate sqlg-h2, sqlg-hsqldb and sqlg-postgres. Or any other solution?

**Comment by pietermartin** [comment]
I am fine with your suggested solution. A PR would be great, tx.

**Comment by jotak** [comment]
No, I wouldn't need it anymore. I would just depend on sqlg-xx-dialect rather than sqlg-xx

**Comment by pietermartin** [comment]
Ok got it.

**Comment by pietermartin** [comment]
Sqlg was still referencing TinkerPop 3.2.2-SNAPSHOT which disappeared.
Its now on 3.2.2 and all is well.
