### ISSUE TITLE
Add H2 support

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#7]
H2 http://www.h2database.com/html/main.html is another java embedded db.
Claims to be faster than HSQLDB

**Comment by metlos** [comment]
I'm almost done with this but H2 has 1 major drawback - it's DDL manipulations are not transactional (i.e. `ALTER TABLE ...; ROLLBACK;` will not cancel the table modification).

How much does Sqlg rely on this? Obviously some scenarios are outlined in the `LoadSchemaTest` (and maybe elsewhere) but is this something Sqlg could guard against using some `supports*()` method and workaround it in some way?

**Comment by pietermartin** [comment]
Hi,
 
Glad to hear you are adding H2 support.

HSQLDB has the same problem as H2.

From what I recall with HSQLDB, is that its even worse than just not rolling back the schema modifications but that is actually implicitly commits the transaction on any schema modification statement. So not only schema modification statements are commited but all statements. It interferes with the user demarcated transaction boundaries which is bad from the applications perspective.

Here are some ideas regarding a work around.

If the underlying db does not support transactional schema creation then that's that.
For such dbs one would have to create the schema upfront and the not allow any lazy schema creation. Or live with the danger of failures and not being sure about the state of the db.
So perhaps a marker to say whether schema creation is allowed or not.

Regarding upfront schema creation.
I have thought about giving sqlg schema definition support. In some sort of TinkerPop property graph json format. Sqlg could then export the definition from an existing graph and users could hand write the script that could be imported/merged on startup. 

Something like that.
Any ideas are welcome.

**Comment by metlos** [comment]
Huh, I completely missed `supportsTransactionalSchema()`. Not that it solves the problems you outlined but hey, the tests now pass! :wink:

**Comment by pietermartin** [comment]
Great, and I completely forgot about `supportsTransactionalSchema()`

**Comment by pietermartin** [comment]
Tx for the PR.
