### ISSUE TITLE
Look at adding Cockroachdb

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#71]
Cockroachdb has added basic join support to their sql.
Its early days but look at adding it as a dialect.

**Comment by JPMoresmau** [comment]
https://www.cockroachlabs.com/blog/cockroachdb-2-0-release/

**Comment by pietermartin** [comment]
I see they mention significant performance improvements which is good as from my first brief look at it, it was slow, as in very slow compared to the regular RDBMS(s) we support. Will be interesting to see how it behaves now.
The other smallish pain point was that they were somewhat inspired by MySql and only support 2 namespaces not 3 like postgresql.

**Comment by pietermartin** [comment]
not interested in this anymore
