### ISSUE TITLE
id

### ISSUE THREAD

**Issue by imhy** [pietermartin/sqlg#74]
Hi!
For find by id  i need g.V("public.Branch:::1")
but this query will not working with neo4j or other graph implementations...
why it is not possible to use g.V(1l) ?

**Comment by pietermartin** [comment]
Sqlg maps labels to a rdbms tables and each table has a regular auto increment primary key.
So "public.Branch:::1" maps to the "Branch" table in the "public" schema with the row's id being 1.
"public.Person:::1" to "Person" table with row's id being 1.

Neo4j implements unique ids across all vertices. I followed this approach for the first iteration of Sqlg but it had rather severe performance implications. I implemented it with a 2 global tables, one for vertices and one for edges. The sole purpose of this was to support Neo4j like globally unique long to identify an element. The global table basically quickly becomes a serious bottle neck. 
`g.V(1)` requires a join as opposed to being a standard select on a single table.
Every insert and delete has to touch this global table.
So all and all it was a bad idea, at least the way I tried to implement it.

Sqlg's current id is actually a `RecordId`.
`g.traversal().V(RecordId.from(SchemaTable.of(g.getSqlDialect().getPublicSchema(), "Person"), 1L))` is the more code heavy way of doing it.
The way you referenced it, is the `String` representation of the `RecordId`

In a way this is similar to `OrientDb` that has the notion of a cluster in their id.

BTW, for what its worth, Neo4j does not recommend referencing a vertex with its id. They consider the id to be an internal implementation detail. The main reason being that they recycle deleted vertices id's on start up so an user can never be entirely sure about a particular id as it might now refer to a completely different id. Still works but alas its the wrong data.

**Comment by imhy** [comment]
Hi! Thank You for reply. Will try not use id for query...

**Comment by pietermartin** [comment]
It is fine to use the id. I use it all the time. In particular for rest calls from the front end.
Also often in backend processing I cache `RecordId`s. 
```
    @Test
    public void testByCollectionOfIds() {
        StopWatch stopWatch = new StopWatch();
        stopWatch.start();
        this.sqlgGraph.tx().streamingWithLockBatchModeOn();
        int count = 1_000_000;
        List<Object> recordIds = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            Vertex v = this.sqlgGraph.addVertex(T.label, "Person");
            recordIds.add(v.id());
        }
        this.sqlgGraph.tx().commit();
        stopWatch.stop();
        System.out.println("insert: " + stopWatch.toString());
        stopWatch.reset();
        stopWatch.start();
        Assert.assertEquals(count, this.sqlgGraph.traversal().V(recordIds).count().next().intValue());
        stopWatch.stop();
        System.out.println("read 1 " + stopWatch.toString());
        stopWatch.reset();
        stopWatch.start();
        Assert.assertEquals(count, this.sqlgGraph.traversal().V().hasId(recordIds).count().next().intValue());
        stopWatch.stop();
        System.out.println("read 2 " + stopWatch.toString());
    }

```

On my laptop this outputs
insert: 0:00:02.089
read 1: 0:00:05.943
read 2: 0:00:03.972

Sqlg has optimized that query.
So no problem to use it.

**Comment by imhy** [comment]
Pieter, thank You for explanation.
