### ISSUE TITLE
*localTime tests fail when local time in non-GMT timezone or possibly DST?

### ISSUE THREAD

**Issue by metlos** [pietermartin/sqlg#76]
I have not dug into this yet, but I just noticed that (at least Postgres) local time tests fail locally for me with an offset of exactly 1 hour.

Not sure yet what might be causing it. Postgres is configured to use the same timezone as the machine itself (both Europe/Prague). So it might be that JVM is misbehaving.. This is on Fedora 24.

**Comment by pietermartin** [comment]
Is the time in the db correct or also of by 1 hour?

**Comment by JPMoresmau** [comment]
I've fixed it. When in batch/stream mode we generate string values for local time, which Postgres evaluate as in UTC. This is why normal access tests still work.

**Comment by JPMoresmau** [comment]
@metlos, can you confirm my fix works for you, so we can close the issue?

**Comment by metlos** [comment]
`PostgresAllTest` passes for me now, but `org.umlg.sqlg.test.tp3.structure.SqlgPostgresStructureStandardTest` has been running for 5hrs now outputting "standard" occassionally. Probably not related but worrying nevertheless.

**Comment by pietermartin** [comment]
Sometimes travis also goes in slow mode and times out. Not sure why. I'd say kill it as it should take a few minutes not hours.

**Comment by JPMoresmau** [comment]
For me, on my machine, it's the TestGratefulDead topology upgrade that hangs, Postgres taking 100% CPU. Sometimes it runs fine...

**Comment by pietermartin** [comment]
Afraid all the time tests are failing on my machine now. Looks like its out by 2 hours. I am in South Africa GMT + 2

**Comment by JPMoresmau** [comment]
Mmhh, I'm not in GMT either, and they pass here. I wonder if there's a setting on the postgres side?

**Comment by pietermartin** [comment]
Are you referring to postgresql.conf timeaone setting?
my postgresql.conf has timezone = 'Africa/Maseru' which is GMT + 2

**Comment by metlos** [comment]
Mine is `timezone = 'Europe/Prague'` which is GMT+2 also...

**Comment by pietermartin** [comment]
And `TestNormalBatchDateTime.batchLocalTime` passes for you?
The LocalTime.now() I passed in to the vertex is "17:13:35.137"
In the postgres table its "19:13:35+02"

**Comment by pietermartin** [comment]
Not really getting whats going on but if the idea was to store UTC then it should probably be "19:13:35+00" not "19:13:35+02"

**Comment by metlos** [comment]
yep, all tests in `TestNormalBatchDateTime` pass for me...

**Comment by pietermartin** [comment]
Ok and just to make sure we are on the same code, your `PostgresDialect` has the `toUTC(LocalTime) ` conversion happening?

**Comment by metlos** [comment]
Yep, I've run the test just now with the latest sqlg master...
Btw, my `Timezone.getDefault().getID()` in java returns 'Europe/Prague', too...

**Comment by pietermartin** [comment]
Ok, so last question, what does the values look like in Postgres, via pgadmin. Same as what I indicated above?

**Comment by JPMoresmau** [comment]
It does for me. The tests pass, and the value is written like 18:53:00+02 in postgres. When I read it gets translated back to the correct time.

**Comment by pietermartin** [comment]
What is your timezone? GMT +1 or +2?

**Comment by JPMoresmau** [comment]
GMT+2. Debugging it, my toUTC conversion is wrong, it uses the offset the wrong way. And it seems that Postgres stores the date with the timezone, so my fix is wrong anyway. So the issue must be something to do with daylight saving time. Is there DST where you live?

**Comment by pietermartin** [comment]
No, South Africa does not have any DST?
France and Czech Republic?

**Comment by JPMoresmau** [comment]
Yep. So if I comment my bad fix and just pass the time as is, it tells me the tz is +2, when I do it outside of batch mode the time is the same but the tz is +1.

**Comment by metlos** [comment]
CZE has DST, but I'm never sure which of the two it actually is - we're now UTC+2, but will be UTC+1 after this weekend ;)

**Comment by JPMoresmau** [comment]
OK, so, if you both can change toUTC to

```
        Time t=Time.valueOf(lt);
        int offset=Calendar.getInstance().get(Calendar.DST_OFFSET)/1000;
        // I know this are deprecated methods, but it's so much clearer than alternatives
    	int m=t.getSeconds();
    	t.setSeconds(m+offset);
    	return t;
```

Do it work for both of you?

Basically we're adding the DST offset since Postgresql in batch mode uses the timezone including DST...

**Comment by pietermartin** [comment]
Its working, nice

**Comment by metlos** [comment]
Yep, works here, too...

**Comment by JPMoresmau** [comment]
I've also checked that 

```
Calendar c=Calendar.getInstance();
        c.set(Calendar.MONTH, 12);
        int offset2=c.get(Calendar.DST_OFFSET)/1000;
```

returns 0 for offset2, meaning that next week when we change to winter time it should still work.

**Comment by JPMoresmau** [comment]
OK, let me clean up and do the PR

**Comment by JPMoresmau** [comment]
International cooperation wins again :+1:

**Comment by pietermartin** [comment]
:+1:
