### ISSUE TITLE
No sorting on Postgres level

### ISSUE THREAD

**Issue by maximmi** [pietermartin/sqlg#77]
I've tried this example with sorting:
http://umlg.org/sqlg.html#OrderID
result set is sorted properly, but actual sql query is missing "order by" clause (I've checker both Sqlg debug as well as Postgres query logs)

I am wondering about performance in case of bigger data set. 
Is it known bug or order not yet supported for Postgres backend?

Thanks
Max

**Comment by pietermartin** [comment]
Sqlg is not able to pass the `order by` down to Postgres for all gremlins. In particular if the query has many leave nodes.

Can you show me the gremlin you are trying to run?

**Comment by maximmi** [comment]
I am trying to run exact same gremlin as in example in docs:

**Comment by pietermartin** [comment]
Ok then its a bug, I'll investigate.

**Comment by maximmi** [comment]
Thanks in advance
