### ISSUE TITLE
Range and Limit do not use SQL

### ISSUE THREAD

**Issue by JPMoresmau** [pietermartin/sqlg#79]
the range and limit Gremlin steps do not translate into SQL, while PostgreSQL at least support these constructs. It's critical for performance. Also linked to #77 , since limiting only makes sense if you specify an order by cause.
I'll happily work on that but I'll need some pointers on where to plug code that says "these Gremlin steps become SQL"...

**Comment by pietermartin** [comment]
Range and limit is just not implemented. #77 is but there is a bug.

**Comment by JPMoresmau** [comment]
I suppose the same is true for count() as well, we could just use select count(*) etc. But some of the code when I try to see what's happening is scary...

**Comment by pietermartin** [comment]
Yeah, gremlin is also scary. However range, limit and count should not be too difficult for simple gremlins.
Its seldom or never possible to always optimize a step. gremlin often does not map to a single sql statement in which case the optimization becomes harder and harder. Currently it only optimizes from the consecutive steps from beginning up to where it can not. The rest of the steps TinkerPop takes care of. Generally the first optimized steps would have narrowed the resultSet so things remain fairly fast.

So for starters `g.V().VertexSteps().range()/limit()` should be easy enough.

I reckon for all currently optimized gremlins, i.e. consecutive vertex steps, optional steps and repeat steps a range/limit at the end should be possible without too much pain.

**Comment by pietermartin** [comment]
count(*) might be different as currently the sql always returns a full vertex. count(*) will probably require special attention. Same with only returning particular properties as opposed to elements. This also a optimization on the TODO list.
