### ISSUE TITLE
Inconsistency on labels cause Gremlin HasStep to fail

### ISSUE THREAD

**Issue by JPMoresmau** [pietermartin/sqlg#90]
The following fails:

```
this.sqlgGraph.addVertex(T.label, "A.A");
this.sqlgGraph.addVertex(T.label, "B.B");
assertEquals(2L,this.sqlgGraph.traversal().V().or(
                __.hasLabel("A.A")
                ,__.hasLabel("B.B")
                   ).count().next().longValue());
```

Because the hasLabel is handled directly by HasStep, which asks for the Vertex label and compares it with the given values. However the vertex label is not schema prefixed, and the values given as arguments are. I suppose changing the behavior of label() on SqlgElement is not reasonable, so we need to substitute these steps by our own...

**Comment by pietermartin** [comment]
Yes I'll have to think about this one. `hasLabel` could appear anywhere in any arbitary gremlin causing the same issue. Relying on substitution is perhaps not the best option.

**Comment by JPMoresmau** [comment]
Ahem. If I add these lines in SqlgElement .label():

```
    	if (this.schema!=null && this.schema.length()>0 && !schema.equals(sqlgGraph.getSqlDialect().getPublicSchema())){
    		return this.schema+"."+this.table;
    	}
```

All existing tests pass, and the traversal that we had failing pass... I would vote to change the behavior that what you get from label() is what you passed to it, so always include the schema (unless the schema is public).

**Comment by pietermartin** [comment]
But the user does not pass the schema to the edge label. Rather it is an implicit technical detail. 
Also it is different to vertex labels in that edge labels are not namespaced but rather the same label is just split between its distinct out vertex labels.
```
        Vertex aa = this.sqlgGraph.addVertex(T.label, "A.A");
        Vertex ab = this.sqlgGraph.addVertex(T.label, "A.B");
        Vertex ba = this.sqlgGraph.addVertex(T.label, "B.A");
        Vertex bb = this.sqlgGraph.addVertex(T.label, "B.B");
        aa.addEdge("ab", ab);
        ba.addEdge("ab", bb);
        this.sqlgGraph.tx().commit();
        assertEquals(2L, this.sqlgGraph.traversal().E().hasLabel("ab").count().next().longValue());
```
i.e. there is only one edge label "ab", "A.ab" and "B.ab" is still the same label which is split in storage across 2 schemas.
Vertex labels are different in that "A.A" is not the same label as "A.B"

So I'd vote to leave the label as just the `this.table` unless we think its a good idea to allow proper namespaceing for edges.
i.e. `g.addEdge(v1, "A.ab")`
Originally I considered that not a good idea as it would start forming a label soup with one not knowing where what is anymore.

On this ticket I was thinking, as I think you were initially saying, to replace all non optimized `HasStep`s with a custom `SqlgHasStep`. I'd need to look at the HasStep implentation again to fully understand if this will work.

**Comment by JPMoresmau** [comment]
Sorry, are you saying you're against namespacing labels for all elements, or just for edges? I can certainly check what the tests give if we do my change ONLY for vertices. It makes sense to get back what you give, so on edges you don't prefix the label, so you don't get a prefixed label.

**Comment by pietermartin** [comment]
Yeah, sorry, I was completely only thinking about edges. For vertices its good.

**Comment by pietermartin** [comment]
BTW, I have spent a mild amount of time thinking about how to plug sql's support for `and` and `or` together with nested brackets `()` into gremlin. In gremlin, it being a fluent language it is hard to express `or`s and `and`s. However sql is very good at it and for sql people it is very natural to use in a `where` clause. Currently this can not be optimized by Sqlg nor will it be trivial but sure will be a a very nice to have.

`g.V().has((this or that) and ((this or that) and somethingelse))` but in proper gremlin
