### ISSUE TITLE
Postgres: wrong data type for autoincrement id columns

### ISSUE THREAD

**Issue by JPMoresmau** [pietermartin/sqlg#91]
In PostgresDialect
```
    @Override
    public String getForeignKeyTypeDefinition() {
        return "BIGINT";
    }

 @Override
    public String getPrimaryKeyType() {
        return "BIGINT NOT NULL PRIMARY KEY";
    }

    @Override
    public String getAutoIncrementPrimaryKeyConstruct() {
        return "SERIAL PRIMARY KEY";
    }
```

The autoincrement should be BIGSERIAL (https://www.postgresql.org/docs/current/static/datatype-numeric.html) to match the other columns, and give us room for IDs. Is it OK to make that change now?

**Comment by pietermartin** [comment]
Yes its ok.

**Comment by pietermartin** [comment]
Can you update CHANGELOG.md for significant changes like this.
