### ISSUE TITLE
Connection leaks in SqlgGraph constructor

### ISSUE THREAD

**Issue by ktschmidt** [pietermartin/sqlg#95]
I am experimenting with running Sqlg in an OSGi runtime (Karaf) where I'm using a JNDI data source that is configured to use a connection pool (HikariCP).  Things are working fine, but I have the connection pool configured to detect connection leaks and it is reporting a couple in the SqlgGraph constructor.

Looking at the code, I see this:

SqlgPlugin p = findSqlgPlugin(this.sqlgDataSource.get(jdbcUrl).getConnection().getMetaData());

which is calling getConnection to get a connection but it is never closed.  Similarly, there is:

this.sqlDialect.prepareDB(this.sqlgDataSource.get(configuration.getString(JDBC_URL)).getConnection());

which is doing the same thing.

The result is two connections are left open and never close.

**Comment by pietermartin** [comment]
@ktschmidt can you confirm that the fix works for you in your environment. tx

**Comment by pietermartin** [comment]
@metlos I don't think we should be closing the connection. Rather just call `rollback()` as the connection is coming from the pool which manages the closing.

**Comment by ktschmidt** [comment]
The primary issue is actually that because the current code just chains the call to getMetaData or passes the connection to the prepareDB method, the connection is never assigned to a variable to be used later nor is it closed.  So it is essentially an orphan that will never be closed unless the garbage collector happens to pick it up and close it.  But because I'm using a connection pool behind the scenes, the connection is still referenced so it won't be garbage collected.  So the connection(s) used in the constructor really should have the close method called on them.

To your other question to @metlos, because I'm using a back-end connection pool, physically closing the connection or not should be left up to that pool and the Sqlg code should simply call Connection.close() when it is done using it.  The pooling implementation will handle returning the connection to the pool and calling rollback so it is in an appropriate state when getConnection is called again and the connection gets returned/reused.

I have a suggested change that does work in my environment that I'll do a pull request for shortly.

**Comment by pietermartin** [comment]
Ok, I was in a bit of a rush getting confused between TinkerPop/Sqlg semantics where the connection is closed on SqlgTransaction.commit/rollBack.

Are you saying that @metlos 's fix of closing the connection does not work for you?

**Comment by ktschmidt** [comment]
@pietermartin my apologies, I did not notice @metlos had checked in a fix. Trying it now.

**Comment by ktschmidt** [comment]
Yes, the fix works for me.  Looking at the code, it is basically the same thing I was testing locally and about to submit a pull request for, so thanks for the quick turnaround!

**Comment by pietermartin** [comment]
Great
